/// \file EnergyCorrectionPlugin.cc
/*
 *
 * EnergyCorrectionPlugin.cc source template automatically generated by a class generator
 * Creation date : mar. nov. 17 2015
 * Updated november 2023 by Tanguy Pasquier
 *
 * This file is part of SDHCALContent libraries.
 * 
 * SDHCALContent is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * SDHCALContent is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SDHCALContent.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */
#include <fstream>
#include "SDHCALPlugins/EnergyCorrectionPlugins.h"
#include "SDHCALHelpers/ClusterHelper.h"

#include "Pandora/AlgorithmHeaders.h"

namespace sdhcal_content
{
  AnalogicEnergyFunction::AnalogicEnergyFunction() :
        m_ecalEnergyType(0),
        m_hcalEnergyType(0),
        m_muonEnergyType(0),
        m_otherEnergyType(0)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode AnalogicEnergyFunction::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    correctedEnergy = 0.f;

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit = *iter;

      const pandora::HitType hitType(pCaloHit->GetHitType());

      const unsigned int energyType(
          (hitType == pandora::ECAL) ? m_ecalEnergyType :
              (hitType == pandora::HCAL) ? m_hcalEnergyType :
                  (hitType == pandora::MUON) ? m_muonEnergyType :
                      m_otherEnergyType);

      switch(energyType)
      {
      case 0:
        correctedEnergy += pCaloHit->GetInputEnergy();
        break;
      case 1:
        correctedEnergy += pCaloHit->GetElectromagneticEnergy();
        break;
      case 2:
        correctedEnergy += pCaloHit->GetHadronicEnergy();
        break;
      default:
        correctedEnergy += pCaloHit->GetInputEnergy();
        break;
      }
    }

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode AnalogicEnergyFunction::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    m_ecalEnergyType = 0;
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "EcalEnergyType", m_ecalEnergyType));

    m_hcalEnergyType = 0;
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "HcalEnergyType", m_hcalEnergyType));

    m_muonEnergyType = 0;
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "MuonEnergyType", m_muonEnergyType));

    m_otherEnergyType = 0;
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "OtherEnergyType", m_otherEnergyType));

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  SdhcalQuadraticEnergyFunction::SdhcalQuadraticEnergyFunction()
  {
    m_energyConstantParameters.push_back(0.0385315);
    m_energyConstantParameters.push_back(4.22584e-05);
    m_energyConstantParameters.push_back(-7.54657e-09);
    m_energyConstantParameters.push_back(0.0784297);
    m_energyConstantParameters.push_back(-5.69439e-05);
    m_energyConstantParameters.push_back(-4.95924e-08);
    m_energyConstantParameters.push_back(0.127212);
    m_energyConstantParameters.push_back(4.56414e-05);
    m_energyConstantParameters.push_back(1.41142e-08);

    m_sdhcalThresholds.push_back(1);
    m_sdhcalThresholds.push_back(2);
    m_sdhcalThresholds.push_back(3);
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode SdhcalQuadraticEnergyFunction::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    unsigned int NHadronicHit  = 0;
    unsigned int NHadronicHit1 = 0;
    unsigned int NHadronicHit2 = 0;
    unsigned int NHadronicHit3 = 0;

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    float emEnergy = 0.f;
    float otherEnergy = 0.f;

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit = *iter;

      // Ecal case. Get the calibrated hit energy
      if(pandora::ECAL == pCaloHit->GetHitType())
      {
        emEnergy += pCaloHit->GetElectromagneticEnergy();
        continue;
      }
      // SDHCAL case. Do thresholds counting
      else if(pandora::HCAL == pCaloHit->GetHitType())
      {
        if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          NHadronicHit1++;
        else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          NHadronicHit2++;
        else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          NHadronicHit3++;
        else
        {
          otherEnergy += pCaloHit->GetInputEnergy();
          continue;
        }

        NHadronicHit++;
      }
      // Other hit types ... should never happen
      else
      {
        otherEnergy += pCaloHit->GetInputEnergy();
      }
    }

    std::ofstream outputFile;
    outputFile.open("/scratch/pasquier/other_energy.txt");
    outputFile << otherEnergy << std::endl;
    outputFile.close();


    // estimate of sdhcal energy
    const float alpha(m_energyConstantParameters.at(0) + m_energyConstantParameters.at(1)*NHadronicHit + m_energyConstantParameters.at(2)*NHadronicHit*NHadronicHit);
    const float beta(m_energyConstantParameters.at(3) + m_energyConstantParameters.at(4)*NHadronicHit + m_energyConstantParameters.at(5)*NHadronicHit*NHadronicHit);
    const float gamma(m_energyConstantParameters.at(6) + m_energyConstantParameters.at(7)*NHadronicHit + m_energyConstantParameters.at(8)*NHadronicHit*NHadronicHit);
    const float hadEnergy(NHadronicHit1*alpha + NHadronicHit2*beta + NHadronicHit3*gamma);

    correctedEnergy = emEnergy + hadEnergy + otherEnergy;

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode SdhcalQuadraticEnergyFunction::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    pandora::FloatVector energyConstantParameters;
    pandora::StatusCode statusCode = pandora::XmlHelper::ReadVectorOfValues(xmlHandle,
        "EnergyConstantParameters", energyConstantParameters);

    if(statusCode == pandora::STATUS_CODE_SUCCESS)
    {
      m_energyConstantParameters = energyConstantParameters;
    }
    else if(statusCode != pandora::STATUS_CODE_NOT_FOUND)
    {
      return statusCode;
    }

    if(9 != m_energyConstantParameters.size())
      return pandora::STATUS_CODE_INVALID_PARAMETER;

    pandora::FloatVector sdhcalThresholds;
    statusCode = pandora::XmlHelper::ReadVectorOfValues(xmlHandle,
        "SdhcalThresholds", sdhcalThresholds);

    if(statusCode == pandora::STATUS_CODE_SUCCESS)
    {
      m_sdhcalThresholds = sdhcalThresholds;
    }
    else if(statusCode != pandora::STATUS_CODE_NOT_FOUND)
    {
      return statusCode;
    }

    if(3 != m_sdhcalThresholds.size())
      return pandora::STATUS_CODE_INVALID_PARAMETER;

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  BarrelGapEnergyFunction::BarrelGapEnergyFunction() :
        m_ecalDistanceToGap(10.f),  // 8 mm + 2 mm
        m_hcalDistanceToGap(30.f),  // 20 mm + 10 mm
        m_ecalGapAlpha(0),
        m_ecalGapBeta(0),
        m_hcalGapAlpha(1.5254),
        m_hcalGapBeta(0)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode BarrelGapEnergyFunction::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
	  //std::cout << "BarrelGapEnergyFunction::MakeEnergyCorrections" << std::endl;
    if(m_ecalZGapPositions.empty() && m_hcalZGapPositions.empty())
      return pandora::STATUS_CODE_SUCCESS;

    if(pCluster->GetNCaloHits() == 0)
      return pandora::STATUS_CODE_SUCCESS;

    float ecalGapEnergy(0), hcalGapEnergy(0);

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit(*iter);
      const bool nearbyGap(this->IsNearbyGap(pCaloHit));

      if(!nearbyGap)
        continue;

      if(pCaloHit->GetHitType() == pandora::ECAL)
        ecalGapEnergy += pCaloHit->GetHadronicEnergy();
      else if(pCaloHit->GetHitType() == pandora::HCAL)
        hcalGapEnergy += pCaloHit->GetHadronicEnergy();
    }

    correctedEnergy +=
        m_ecalGapAlpha * ecalGapEnergy + m_ecalGapBeta * ecalGapEnergy * ecalGapEnergy +
        m_hcalGapAlpha * hcalGapEnergy + m_hcalGapBeta * hcalGapEnergy * hcalGapEnergy;

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  bool BarrelGapEnergyFunction::IsNearbyGap(const pandora::CaloHit *const pCaloHit) const
  {
    if(pCaloHit->GetHitRegion() != pandora::BARREL)
      return false;

    if(pCaloHit->GetHitType() != pandora::ECAL && pCaloHit->GetHitType() != pandora::HCAL)
      return false;

    const pandora::FloatVector zGapPositions(pCaloHit->GetHitType() == pandora::ECAL ? m_ecalZGapPositions : m_hcalZGapPositions);
    const float distanceToGap(pCaloHit->GetHitType() == pandora::ECAL ? m_ecalDistanceToGap : m_hcalDistanceToGap);
    const float hitZ(pCaloHit->GetPositionVector().GetZ());

    for(pandora::FloatVector::const_iterator iter = zGapPositions.begin(), endIter = zGapPositions.end() ;
        endIter != iter ; ++iter)
    {
      const float gapZPosition(*iter);

      if( ((hitZ < gapZPosition) && (hitZ > gapZPosition-distanceToGap))
       || ((hitZ > gapZPosition) && (hitZ < gapZPosition+distanceToGap)) )
      {
        return true;
      }
    }

    return false;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode BarrelGapEnergyFunction::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadVectorOfValues(xmlHandle,
        "EcalZGapPositions", m_ecalZGapPositions));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadVectorOfValues(xmlHandle,
        "HcalZGapPositions", m_hcalZGapPositions));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "EcalDistanceToGap", m_ecalDistanceToGap));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "HcalDistanceToGap", m_hcalDistanceToGap));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "EcalGapAlpha", m_ecalGapAlpha));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "EcalGapBeta", m_ecalGapBeta));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "HcalGapAlpha", m_hcalGapAlpha));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "HcalGapBeta", m_hcalGapBeta));

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  ThetaNHitFunction::ThetaNHitFunction() :
       m_lowEnergyCut(3.f)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode ThetaNHitFunction::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    pandora::FloatVector m_sdhcalThresholds; //Vector to store the thresholds used
    if(m_useDigi)
    {
      m_sdhcalThresholds.push_back(1);
      m_sdhcalThresholds.push_back(2);
      m_sdhcalThresholds.push_back(3);
    }
    else 
    {
      m_sdhcalThresholds.push_back(0.0367023);
      m_sdhcalThresholds.push_back(0.0745279);
      m_sdhcalThresholds.push_back(0.363042);
    }
    //unsigned int NHadronicHit = 0;
    unsigned int NHadronicHit1 = 0;
    unsigned int NHadronicHit2 = 0;
    unsigned int NHadronicHit3 = 0;
  
    unsigned int barrelNHadronicHit1 = 0;
    unsigned int barrelNHadronicHit2 = 0;
    unsigned int barrelNHadronicHit3 = 0;

    unsigned int endcapNHadronicHit1 = 0;
    unsigned int endcapNHadronicHit2 = 0; 
    unsigned int endcapNHadronicHit3 = 0; 

    float initialHadronic = 0;

    float emEnergy = 0;

    if(pCluster->GetNCaloHits() == 0)
      return pandora::STATUS_CODE_SUCCESS;

    if(correctedEnergy < m_lowEnergyCut)
      return pandora::STATUS_CODE_SUCCESS;

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    bool noShowerHit(true);

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit(*iter);

      if(pCaloHit->GetHitType() == pandora::ECAL) //Only focus on SDHCAL corrections
      {
        emEnergy += pCaloHit->GetElectromagneticEnergy();
      }

      if(pCaloHit->GetHitType() == pandora::HCAL)
        {
          if(pCaloHit->GetHitRegion() == pandora::BARREL)
          {
            if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              barrelNHadronicHit1++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.0367023;
            }
            else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              barrelNHadronicHit2++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.0745279;
            }
            else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              barrelNHadronicHit3++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.363042;
            }
          }
          else if(pCaloHit->GetHitRegion() == pandora::ENDCAP)
          {
            if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            { 
              endcapNHadronicHit1++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.0367023;
            }
            else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              endcapNHadronicHit2++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.0745279;
            }
            else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              endcapNHadronicHit3++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.363042;
            }
          }
          noShowerHit = false;
        }
    }

    if(noShowerHit)
      return pandora::STATUS_CODE_SUCCESS;

    correctedEnergy-=initialHadronic; // Pull the initial energy of the HCAL hits from the total energy to correct

    /* std::cout << "NHadronicHit : " << NHadronicHit << std::endl;
    std::cout << "barrelNHadronicHit1 : " << barrelNHadronicHit1 << std::endl;
    std::cout << "barrelNHadronicHit2 : " << barrelNHadronicHit2 << std::endl;
    std::cout << "barrelNHadronicHit3 : " << barrelNHadronicHit3 << std::endl;

    std::cout << "endcapNHadronicHit1 : " << endcapNHadronicHit1 << std::endl;
    std::cout << "endcapNHadronicHit2 : " << endcapNHadronicHit2 << std::endl;
    std::cout << "endcapNHadronicHit3 : " << endcapNHadronicHit3 << std::endl; */

    //Parameters for geometric theta correction
    const float clusterCosTheta(this->GetCosTheta(pCluster)); //Cos theta for the endcap correction
    const float thetaAngle(std::acos(clusterCosTheta)); //Theta angle
    const float clusterSinTheta(std::sin(thetaAngle)); //Sin theta for the barrel correction

    //Sum the corrected number of hits for each tresholds
    NHadronicHit1 = this->GetCorrectedHitNumber(barrelNHadronicHit1, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit1, clusterCosTheta);
    NHadronicHit2 = this->GetCorrectedHitNumber(barrelNHadronicHit2, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit2, clusterCosTheta);
    NHadronicHit3 = this->GetCorrectedHitNumber(barrelNHadronicHit3, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit3, clusterCosTheta);

    /* //Calculate the corrected total number of hits
    NHadronicHit = NHadronicHit1 + NHadronicHit2 + NHadronicHit3;

    //std::cout << "NHit corrected : " << NHadronicHit << std::endl;

    pandora::FloatVector m_energyConstantParameters;

    m_energyConstantParameters.push_back(0.0385315);
    m_energyConstantParameters.push_back(4.22584e-05);
    m_energyConstantParameters.push_back(-7.54657e-09);
    m_energyConstantParameters.push_back(0.0784297);
    m_energyConstantParameters.push_back(-5.69439e-05);
    m_energyConstantParameters.push_back(-4.95924e-08);
    m_energyConstantParameters.push_back(0.127212);
    m_energyConstantParameters.push_back(4.56414e-05);
    m_energyConstantParameters.push_back(1.41142e-08);

    // Quadratic correction
    const float alpha(m_energyConstantParameters.at(0) + m_energyConstantParameters.at(1)*NHadronicHit + m_energyConstantParameters.at(2)*NHadronicHit*NHadronicHit);
    const float beta(m_energyConstantParameters.at(3) + m_energyConstantParameters.at(4)*NHadronicHit + m_energyConstantParameters.at(5)*NHadronicHit*NHadronicHit);
    const float gamma(m_energyConstantParameters.at(6) + m_energyConstantParameters.at(7)*NHadronicHit + m_energyConstantParameters.at(8)*NHadronicHit*NHadronicHit);
    const float hadEnergy(NHadronicHit1*alpha + NHadronicHit2*beta + NHadronicHit3*gamma); */

    //const float hadEnergy(NHadronicHit1*0.0367023 + NHadronicHit2*0.0745279 + NHadronicHit3*0.363042); //Initial parameters
    //float hadEnergy(1.77366 + 0.33832*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000868032*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde
    float hadEnergy(1.77366 + 0.32832*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000858032*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde, test 3

    //correctedEnergy += hadEnergy; //Compute the corrected energy

    correctedEnergy = emEnergy + hadEnergy;

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float ThetaNHitFunction::GetCosTheta(const pandora::Cluster *const pCluster) const
  {
    pandora::CartesianVector centroid(0.f, 0.f, 0.f);
    PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));

    return fabs(centroid.GetCosOpeningAngle(pandora::CartesianVector(0.f, 0.f, 1.f)));
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float ThetaNHitFunction::GetCorrectedHitNumber(int nHit, float cosTheta) const
  {
	  //std::cout << "nHit: " << nHit << ", cosTheta: " << cosTheta << std::endl;
    return nHit * (1 / (cosTheta));
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode ThetaNHitFunction::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "LowEnergyCut", m_lowEnergyCut));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "UseDigi", m_useDigi));

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  PhiNHitTesla::PhiNHitTesla() :
       m_lowEnergyCut(3.f)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode PhiNHitTesla::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    pandora::FloatVector m_sdhcalThresholds; //Vector to store the thresholds used
    if(m_useDigi)
    {
      m_sdhcalThresholds.push_back(1);
      m_sdhcalThresholds.push_back(2);
      m_sdhcalThresholds.push_back(3);
    }
    else 
    {
      m_sdhcalThresholds.push_back(0.0367023);
      m_sdhcalThresholds.push_back(0.0745279);
      m_sdhcalThresholds.push_back(0.363042);
    }
    
    unsigned int NHadronicHit1 = 0;
    unsigned int NHadronicHit2 = 0;
    unsigned int NHadronicHit3 = 0;
  
    unsigned int barrelNHadronicHit1 = 0;
    unsigned int barrelNHadronicHit2 = 0;
    unsigned int barrelNHadronicHit3 = 0; 

    float initialBarrelHadronic = 0;

    if(pCluster->GetNCaloHits() == 0)
      return pandora::STATUS_CODE_SUCCESS;

    if(correctedEnergy < m_lowEnergyCut)
      return pandora::STATUS_CODE_SUCCESS;

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    bool noShowerHit(true);

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit(*iter);

      if(pCaloHit->GetHitType() == pandora::HCAL)
        {
          if(pCaloHit->GetHitRegion() == pandora::BARREL)
          {
            if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            { 
              barrelNHadronicHit1++;
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.0367023;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }
            }
            else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              barrelNHadronicHit2++;
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.0745279;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }
            }
            else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              barrelNHadronicHit3++;
              
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.363042;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }
            }
          }
          noShowerHit = false;
        }
    }

    if(noShowerHit)
      return pandora::STATUS_CODE_SUCCESS;

    correctedEnergy-=initialBarrelHadronic; // Pull the initial energy of the HCAL hits from the total energy to correct

    /* std::cout << "NHadronicHit : " << NHadronicHit << std::endl;
    std::cout << "barrelNHadronicHit1 : " << barrelNHadronicHit1 << std::endl;
    std::cout << "barrelNHadronicHit2 : " << barrelNHadronicHit2 << std::endl;
    std::cout << "barrelNHadronicHit3 : " << barrelNHadronicHit3 << std::endl; */

    //Parameters for geometric phi correction
    const float clusterCosPhi(this->GetCosPhi(pCluster)); //Cos theta for the endcap correction

    //Sum the corrected number of hits for each tresholds
    NHadronicHit1 = this->GetCorrectedHitNumber(barrelNHadronicHit1, clusterCosPhi);
    NHadronicHit2 = this->GetCorrectedHitNumber(barrelNHadronicHit2, clusterCosPhi);
    NHadronicHit3 = this->GetCorrectedHitNumber(barrelNHadronicHit3, clusterCosPhi);

    const float correctedBarrelEnergy(NHadronicHit1*0.0367023 + NHadronicHit2*0.0745279 + NHadronicHit3*0.363042); //New barrel hadronic energy
    correctedEnergy += correctedBarrelEnergy; //Compute the corrected energy
   
    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float PhiNHitTesla::GetCosPhi(const pandora::Cluster *const pCluster) const
  {
    pandora::CartesianVector centroid(0.f, 0.f, 0.f);
    pandora::CartesianVector zAxis(0.f, 0.f, 1.f);
  
    PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));
    pandora::CartesianVector projectedCentroid(zAxis.GetCrossProduct(centroid.GetCrossProduct(zAxis))); //Project the postion vector of the cluster in the XY-plane 
    float phiAngle = projectedCentroid.GetOpeningAngle(pandora::CartesianVector(0.f, 1.f, 0.f)); //Returns an angle between 0 and PI in rad
    while(phiAngle>M_PI_4/2) //Substract PI/4 until the angle is between -PI/8 and PI/8 rad
    {
        phiAngle-=M_PI_4;
    }

    return fabs(std::cos(phiAngle)); 
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float PhiNHitTesla::GetCorrectedHitNumber(int nHit, float cosPhi) const
  {
	  //std::cout << "nHit: " << nHit << ", cosTheta: " << cosTheta << std::endl;
    return nHit * (1 / (cosPhi));
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode PhiNHitTesla::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "LowEnergyCut", m_lowEnergyCut));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "UseDigi", m_useDigi));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "ThetaBefore", m_thetaBefore));

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  PhiNHitVideau::PhiNHitVideau() :
       m_lowEnergyCut(3.f)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode PhiNHitVideau::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    pandora::FloatVector m_sdhcalThresholds; //Vector to store the thresholds used
    if(m_useDigi)
    {
      m_sdhcalThresholds.push_back(1);
      m_sdhcalThresholds.push_back(2);
      m_sdhcalThresholds.push_back(3);
    }
    else 
    {
      m_sdhcalThresholds.push_back(0.0367023);
      m_sdhcalThresholds.push_back(0.0745279);
      m_sdhcalThresholds.push_back(0.363042);
    }

    unsigned int NHadronicHit1 = 0;
    unsigned int NHadronicHit2 = 0;
    unsigned int NHadronicHit3 = 0;
  
    unsigned int firstNHadronicHit1 = 0; //For the hits contained in the first calo block in Videau geometry
    unsigned int firstNHadronicHit2 = 0;
    unsigned int firstNHadronicHit3 = 0; 

    unsigned int secondNHadronicHit1 = 0; //For the hits contained in the second calo block in Videau geometry
    unsigned int secondNHadronicHit2 = 0;
    unsigned int secondNHadronicHit3 = 0; 

    float initialBarrelHadronic = 0;

    if(pCluster->GetNCaloHits() == 0)
      return pandora::STATUS_CODE_SUCCESS;

    if(correctedEnergy < m_lowEnergyCut)
      return pandora::STATUS_CODE_SUCCESS;

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    bool noShowerHit(true);

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit(*iter);

      if(pCaloHit->GetHitType() == pandora::HCAL)
        {
          if(pCaloHit->GetHitRegion() == pandora::BARREL)
          {
            if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            { 
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.0367023;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }

              if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
                firstNHadronicHit1++;
              else
                secondNHadronicHit1++;
            }
            else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.0745279;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }

              if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
                firstNHadronicHit2++;
              else
                secondNHadronicHit2++;
            }
            else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.363042;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }

              if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
                firstNHadronicHit3++;
              else
                secondNHadronicHit3++;
            }
          }
          noShowerHit = false;
        }
    }

    if(noShowerHit)
      return pandora::STATUS_CODE_SUCCESS;

    correctedEnergy-=initialBarrelHadronic; // Pull the initial energy of the HCAL hits from the total energy to correct

    /* std::cout << "NHadronicHit : " << NHadronicHit << std::endl;
    std::cout << "barrelNHadronicHit1 : " << barrelNHadronicHit1 << std::endl;
    std::cout << "barrelNHadronicHit2 : " << barrelNHadronicHit2 << std::endl;
    std::cout << "barrelNHadronicHit3 : " << barrelNHadronicHit3 << std::endl; */

    //Parameters for geometric phi correction
    const float clusterCosPhi(this->GetCosPhi(pCluster)); //Cos phi for the fisrt calo block

    //Angle for the second calo block
    const float PhiPrime(M_PI_4 - std::acos(this->GetCosPhi(pCluster))); //PhiPrime angle with respect to the second calo block

    //CosPhiPrime
    const float clusterCosPhiPrime(fabs(std::cos(PhiPrime))); //Cos phi for the fisrt calo block

    //Sum the corrected number of hits for each tresholds
    NHadronicHit1 = this->GetCorrectedHitNumber(firstNHadronicHit1, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit1, clusterCosPhiPrime);
    NHadronicHit2 = this->GetCorrectedHitNumber(firstNHadronicHit2, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit2, clusterCosPhiPrime);
    NHadronicHit3 = this->GetCorrectedHitNumber(firstNHadronicHit3, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit3, clusterCosPhiPrime);

    const float correctedBarrelEnergy(NHadronicHit1*0.0367023 + NHadronicHit2*0.0745279 + NHadronicHit3*0.363042); //New barrel hadronic energy
    correctedEnergy += correctedBarrelEnergy; //Compute the corrected energy

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float PhiNHitVideau::GetCosPhi(const pandora::Cluster *const pCluster) const
  {
    pandora::CartesianVector centroid(0.f, 0.f, 0.f);
    pandora::CartesianVector zAxis(0.f, 0.f, 1.f);
  
    PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));
    pandora::CartesianVector projectedCentroid(zAxis.GetCrossProduct(centroid.GetCrossProduct(zAxis))); //Project the postion vector of the cluster in the XY-plane 
    float phiAngle = projectedCentroid.GetOpeningAngle(pandora::CartesianVector(0.f, 1.f, 0.f)); //Returns an angle between 0 and PI in rad
    while(phiAngle>M_PI_4/2) //Substract PI/4 until the angle is between -PI/8 and PI/8 rad
    {
        phiAngle-=M_PI_4;
    }

    return fabs(std::cos(phiAngle)); 
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float PhiNHitVideau::GetCorrectedHitNumber(int nHit, float cosPhi) const
  {
	  //std::cout << "nHit: " << nHit << ", cosTheta: " << cosTheta << std::endl;
    return nHit * (1 / (cosPhi));
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode PhiNHitVideau::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "LowEnergyCut", m_lowEnergyCut));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "UseDigi", m_useDigi));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "ThetaBefore", m_thetaBefore));

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  AngleCorrectionPlugin::AngleCorrectionPlugin() :
       m_lowEnergyCut(3.f)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode AngleCorrectionPlugin::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    pandora::FloatVector m_sdhcalThresholds; //Vector to store the thresholds used

    if(m_useDigi)
    {
      m_sdhcalThresholds.push_back(1);
      m_sdhcalThresholds.push_back(2);
      m_sdhcalThresholds.push_back(3);
    }
    else 
    {
      m_sdhcalThresholds.push_back(0.0367023);
      m_sdhcalThresholds.push_back(0.0745279);
      m_sdhcalThresholds.push_back(0.363042);
    }

    unsigned int NHadronicHit = 0;
    unsigned int NHadronicHit1 = 0;
    unsigned int NHadronicHit2 = 0;
    unsigned int NHadronicHit3 = 0;

    unsigned int initialNHit1 = 0;
    unsigned int initialNHit2 = 0;
    unsigned int initialNHit3 = 0;
  
    unsigned int barrelNHadronicHit1 = 0; //For the theta correction in the barrel
    unsigned int barrelNHadronicHit2 = 0;
    unsigned int barrelNHadronicHit3 = 0;

    unsigned int endcapNHadronicHit1 = 0; //For the theta correction in the endcap
    unsigned int endcapNHadronicHit2 = 0; 
    unsigned int endcapNHadronicHit3 = 0; 

    unsigned int firstNHadronicHit1 = 0; //For the phi correction in the first calo block in Videau geometry
    unsigned int firstNHadronicHit2 = 0;
    unsigned int firstNHadronicHit3 = 0; 

    unsigned int secondNHadronicHit1 = 0; //For the phi correction in the second calo block in Videau geometry
    unsigned int secondNHadronicHit2 = 0;
    unsigned int secondNHadronicHit3 = 0; 

    float initialHadronic = 0;

    float lumiHCALEnergy = 0;

    float emEnergy = 0;

    //std::cout << "CORRECTED INIT : " << correctedEnergy << std::endl;

    if(pCluster->GetNCaloHits() == 0)
      return pandora::STATUS_CODE_SUCCESS;
    
    if(correctedEnergy < m_lowEnergyCut)
      return pandora::STATUS_CODE_SUCCESS;

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    bool noShowerHit(true);

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit(*iter);

      if(pCaloHit->GetHitType() == pandora::ECAL) //Only focus on SDHCAL corrections
      {
        emEnergy += pCaloHit->GetElectromagneticEnergy();
        noShowerHit = false;
      }

      else if(pCaloHit->GetHitType() == pandora::HCAL) //Only focus on SDHCAL corrections
      {
        if(pCaloHit->GetHitRegion() == pandora::BARREL)
        {
          //std::cout << pCaloHit->GetCellNormalVector() << std::endl;
          if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          {
            initialHadronic+=pCaloHit->GetHadronicEnergy();
            if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
              firstNHadronicHit1++;
            else
              secondNHadronicHit1++;
          }
          else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          {
            initialHadronic+=pCaloHit->GetHadronicEnergy();
            if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
              firstNHadronicHit2++;
            else
              secondNHadronicHit2++;
          }
          else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          {
            initialHadronic+=pCaloHit->GetHadronicEnergy();
            if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
              firstNHadronicHit3++;
            else
              secondNHadronicHit3++;
          }
        }
        else if(pCaloHit->GetHitRegion() == pandora::ENDCAP)
        {
          if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          { 
            endcapNHadronicHit1++;
            initialHadronic+=pCaloHit->GetHadronicEnergy();
          }
          else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          {
            endcapNHadronicHit2++;
            initialHadronic+=pCaloHit->GetHadronicEnergy();
          }
          else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          {
            endcapNHadronicHit3++;
            initialHadronic+=pCaloHit->GetHadronicEnergy();
          }
          else
          {
            lumiHCALEnergy+=pCaloHit->GetHadronicEnergy();
          }
        }
        noShowerHit = false;
      }
    }

    if(noShowerHit)
      return pandora::STATUS_CODE_SUCCESS;

    //correctedEnergy-=initialHadronic; // Pull the initial energy of the HCAL hits from the total energy to correct

    //std::cout << "WITHOUT INITIAL : " << correctedEnergy << std::endl;

    barrelNHadronicHit1 = firstNHadronicHit1 + secondNHadronicHit1; //Sum the hits in the barrel
    barrelNHadronicHit2 = firstNHadronicHit2 + secondNHadronicHit2;
    barrelNHadronicHit3 = firstNHadronicHit3 + secondNHadronicHit3;

    /* std::cout << "N1 premier stave : " << firstNHadronicHit1 << std::endl;
    std::cout << "N2 premier stave : " << firstNHadronicHit2 << std::endl;
    std::cout << "N3 premier stave : " << firstNHadronicHit3 << std::endl;

    std::cout << "N1 deuxieme stave : " << secondNHadronicHit1 << std::endl;
    std::cout << "N2 deuxieme stave : " << secondNHadronicHit2 << std::endl;
    std::cout << "N3 deuxieme stave : " << secondNHadronicHit3 << std::endl; */

    initialNHit1 = barrelNHadronicHit1 + endcapNHadronicHit1; //Compute the initial number of hits in sdhcal
    initialNHit2 = barrelNHadronicHit2 + endcapNHadronicHit2;
    initialNHit3 = barrelNHadronicHit3 + endcapNHadronicHit3;

    /* std::cout << "NHadronicHit : " << NHadronicHit << std::endl;
    std::cout << "barrelNHadronicHit1 : " << barrelNHadronicHit1 << std::endl;
    std::cout << "barrelNHadronicHit2 : " << barrelNHadronicHit2 << std::endl;
    std::cout << "barrelNHadronicHit3 : " << barrelNHadronicHit3 << std::endl;

    std::cout << "endcapNHadronicHit1 : " << endcapNHadronicHit1 << std::endl;
    std::cout << "endcapNHadronicHit2 : " << endcapNHadronicHit2 << std::endl;
    std::cout << "endcapNHadronicHit3 : " << endcapNHadronicHit3 << std::endl; */

    //TO UNCOMMENT WHEN NOT USING THE FIXDIRECTION DISPLACED TESLA

     //Parameters for geometric phi correction
    const float clusterCosPhi(this->GetCosPhi(pCluster)); //Cos phi for the fisrt calo block

    //std::cout << "Phi : " << std::acos(clusterCosPhi) * (180 /M_PI) << std::endl;

    //Angle for the second calo block
    const float PhiPrime(M_PI_4 - std::acos(this->GetCosPhi(pCluster))); //PhiPrime angle with respect to the second calo block
    //std::cout << "Phi Prime : " << PhiPrime * (180 /M_PI)<< std::endl;

    //CosPhiPrime
    const float clusterCosPhiPrime(fabs(std::cos(PhiPrime))); //Cos phi for the fisrt calo block

    //Parameters for geometric theta correction
    const float clusterCosTheta(this->GetCosTheta(pCluster)); //Cos theta for the endcap correction
    const float thetaAngle(std::acos(clusterCosTheta)); //Theta angle
    const float clusterSinTheta(std::sin(thetaAngle)); //Sin thecosOrSinAngla for the barrel correction 

    //Sum the corrected number of hits for each tresholds
    NHadronicHit1 = initialNHit1 + this->GetCorrectedHitNumber(barrelNHadronicHit1, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit1, clusterCosTheta) + this->GetCorrectedHitNumber(firstNHadronicHit1, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit1, clusterCosPhiPrime);
    NHadronicHit2 = initialNHit2 + this->GetCorrectedHitNumber(barrelNHadronicHit2, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit2, clusterCosTheta) + this->GetCorrectedHitNumber(firstNHadronicHit2, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit2, clusterCosPhiPrime);
    NHadronicHit3 = initialNHit3 + this->GetCorrectedHitNumber(barrelNHadronicHit3, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit3, clusterCosTheta) + this->GetCorrectedHitNumber(firstNHadronicHit3, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit3, clusterCosPhiPrime);
 
    /* NHadronicHit1 = initialNHit1 + this->GetCorrectedHitNumber(firstNHadronicHit1, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit1, clusterCosPhiPrime);
    NHadronicHit2 = initialNHit2 + this->GetCorrectedHitNumber(firstNHadronicHit2, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit2, clusterCosPhiPrime);
    NHadronicHit3 = initialNHit3 + this->GetCorrectedHitNumber(firstNHadronicHit3, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit3, clusterCosPhiPrime);
 */

    //For fixdirection displaced Tesla 
    /* NHadronicHit1 = initialNHit1;
    NHadronicHit2 = initialNHit2;
    NHadronicHit3 = initialNHit3; */


    //Calculate the corrected total number of hits
    NHadronicHit = NHadronicHit1 + NHadronicHit2 + NHadronicHit3;

    //std::cout << "NHit corrected : " << NHadronicHit << std::endl;

    pandora::FloatVector m_energyConstantParameters;

    /* m_energyConstantParameters.push_back(0.0385315); //Initial in the program
    m_energyConstantParameters.push_back(4.22584e-05);
    m_energyConstantParameters.push_back(-7.54657e-09);
    m_energyConstantParameters.push_back(0.0784297);
    m_energyConstantParameters.push_back(-5.69439e-05);
    m_energyConstantParameters.push_back(-4.95924e-08);
    m_energyConstantParameters.push_back(0.127212);
    m_energyConstantParameters.push_back(4.56414e-05);
    m_energyConstantParameters.push_back(1.41142e-08); */

   /*  m_energyConstantParameters.push_back(0.0627833); //Test avec grosse parabole sur le gamma, nomme Quad_test_1, MARCHE BIEN
    m_energyConstantParameters.push_back(-0.000110457);
    m_energyConstantParameters.push_back(6.97355e-08);
    m_energyConstantParameters.push_back(0.067663);
    m_energyConstantParameters.push_back(8.42064e-05);
    m_energyConstantParameters.push_back(-5.44862e-08);
    m_energyConstantParameters.push_back(-0.014136);
    m_energyConstantParameters.push_back(0.00116875);
    m_energyConstantParameters.push_back(-7.38563e-07);  */

    /* m_energyConstantParameters.push_back(0.0698009); //Test avec juste Ntot=0 et gamma1 positif, nomme Quad_test_2, MARCHE BIEN AUSSI
    m_energyConstantParameters.push_back(-9.58617e-05);
    m_energyConstantParameters.push_back(5.24263e-08);
    m_energyConstantParameters.push_back(0.0352866);
    m_energyConstantParameters.push_back(0.000139652);
    m_energyConstantParameters.push_back(-7.83021e-08);
    m_energyConstantParameters.push_back(2.68496e-15);
    m_energyConstantParameters.push_back(0.000885865);
    m_energyConstantParameters.push_back(-5.023e-07); */

    /* if(pCluster->GetNCaloHits() > 400) //Deuxieme test de split avec la formule Quad test 2 et l'autre formule : TRES BON !
    {
      m_energyConstantParameters.push_back(0.0698009); //Meme parametres que pour le Quad_test_2, mais avec le terme linéaire d'alpha boosté, Quad_test_3, Tres bon en linearite mais moins en résolution, J'AI GARDE LUI POUR LES PLOTS
      m_energyConstantParameters.push_back(-9.08617e-05);
      m_energyConstantParameters.push_back(5.24263e-08);
      m_energyConstantParameters.push_back(0.0352866);
      m_energyConstantParameters.push_back(0.000139652);
      m_energyConstantParameters.push_back(-7.83021e-08);
      m_energyConstantParameters.push_back(2.68496e-15);
      m_energyConstantParameters.push_back(0.000885865);
      m_energyConstantParameters.push_back(-5.023e-07);
    }
    else
    {
      m_energyConstantParameters.push_back(0.0772817); //Parametres pour Ntot < 400
      m_energyConstantParameters.push_back(-0.000201997);
      m_energyConstantParameters.push_back(2.75701e-07);
      m_energyConstantParameters.push_back(0.0717378);
      m_energyConstantParameters.push_back(8.39357e-05);
      m_energyConstantParameters.push_back(-1.30498e-07);
      m_energyConstantParameters.push_back(9.50033e-11);
      m_energyConstantParameters.push_back(0.000751526);
      m_energyConstantParameters.push_back(-1.67637e-07);
    } */

   /*  if(pCluster->GetNCaloHits() > 400) //Troisieme test de split propre avec ajustement sur chaque range de la quadratique classique -> Donne trop peu de fichier (valeurs négatives ?)
    {
      m_energyConstantParameters.push_back(0.0859395);
      m_energyConstantParameters.push_back(-0.000132893);
      m_energyConstantParameters.push_back(7.18543e-08);
      m_energyConstantParameters.push_back(-0.0275535);
      m_energyConstantParameters.push_back(0.000290422);
      m_energyConstantParameters.push_back(-1.60087e-07);
      m_energyConstantParameters.push_back(2.64258e-11);
      m_energyConstantParameters.push_back(0.000863202);
      m_energyConstantParameters.push_back(-4.81296e-07);
    }
    else
    {
      m_energyConstantParameters.push_back(0.077717);
      m_energyConstantParameters.push_back(-0.000265804);
      m_energyConstantParameters.push_back(3.72629e-07);
      m_energyConstantParameters.push_back(0.0531516);
      m_energyConstantParameters.push_back(0.000280523);
      m_energyConstantParameters.push_back(-4.16125e-07);
      m_energyConstantParameters.push_back(9.16431e-11);
      m_energyConstantParameters.push_back(0.00140285);
      m_energyConstantParameters.push_back(-1.53288e-06);
    } */

    /* if(pCluster->GetNCaloHits() > 400) //Quatrieme test de split propre avec ajustement sur chaque range de la quadratique classique
    {
      m_energyConstantParameters.push_back(0.0790412);
      m_energyConstantParameters.push_back(-0.0001142);
      m_energyConstantParameters.push_back(6.08164e-08);
      m_energyConstantParameters.push_back(9.98997e-11);
      m_energyConstantParameters.push_back(0.000216286);
      m_energyConstantParameters.push_back(-1.16695e-07);
      m_energyConstantParameters.push_back(9.88261e-11);
      m_energyConstantParameters.push_back(0.000864327);
      m_energyConstantParameters.push_back(-4.8178e-07);
    }
    else
    {
      m_energyConstantParameters.push_back(0.077717);
      m_energyConstantParameters.push_back(-0.000265804);
      m_energyConstantParameters.push_back(3.72629e-07);
      m_energyConstantParameters.push_back(0.0531516);
      m_energyConstantParameters.push_back(0.000280523);
      m_energyConstantParameters.push_back(-4.16125e-07);
      m_energyConstantParameters.push_back(9.16431e-11);
      m_energyConstantParameters.push_back(0.00140285);
      m_energyConstantParameters.push_back(-1.53288e-06);
    } */

    /* if(pCluster->GetNCaloHits() > 600) //Cinquieme test de split propre avec ajustement sur chaque range de la quadratique classique et seuil a 600
    {
      m_energyConstantParameters.push_back(0.0830988);
      m_energyConstantParameters.push_back(-0.000122872);
      m_energyConstantParameters.push_back(6.53792e-08);
      m_energyConstantParameters.push_back(9.98381e-11);
      m_energyConstantParameters.push_back(0.000211478);
      m_energyConstantParameters.push_back(-1.11879e-07);
      m_energyConstantParameters.push_back(9.86698e-11);
      m_energyConstantParameters.push_back(0.000914441);
      m_energyConstantParameters.push_back(-5.29149e-07);
    }
    else
    {
      m_energyConstantParameters.push_back(0.0644737);
      m_energyConstantParameters.push_back(-0.000105861);
      m_energyConstantParameters.push_back(7.19378e-08);
      m_energyConstantParameters.push_back(0.0720974);
      m_energyConstantParameters.push_back(8.3249e-05);
      m_energyConstantParameters.push_back(-8.67671e-08);
      m_energyConstantParameters.push_back(0.0106789);
      m_energyConstantParameters.push_back(0.000895708);
      m_energyConstantParameters.push_back(-5.02596e-07);
    } */

    /* if(pCluster->GetNCaloHits() > 500) //Test de split propre avec ajustement sur chaque range de la quadratique classique + chevauchement et seuil a 500
    {
      m_energyConstantParameters.push_back(0.0790412);  //Parametres fit sur Ntot > 400
      m_energyConstantParameters.push_back(-0.0001142);
      m_energyConstantParameters.push_back(6.08164e-08);
      m_energyConstantParameters.push_back(9.98997e-11);
      m_energyConstantParameters.push_back(0.000216286);
      m_energyConstantParameters.push_back(-1.16695e-07);
      m_energyConstantParameters.push_back(9.88261e-11);
      m_energyConstantParameters.push_back(0.000864327);
      m_energyConstantParameters.push_back(-4.8178e-07);
    }
    else
    {
      m_energyConstantParameters.push_back(0.0644737); //Parametres fit sur Ntot < 600
      m_energyConstantParameters.push_back(-0.000105861);
      m_energyConstantParameters.push_back(7.19378e-08);
      m_energyConstantParameters.push_back(0.0720974);
      m_energyConstantParameters.push_back(8.3249e-05);
      m_energyConstantParameters.push_back(-8.67671e-08);
      m_energyConstantParameters.push_back(0.0106789);
      m_energyConstantParameters.push_back(0.000895708);
      m_energyConstantParameters.push_back(-5.02596e-07);
    } */

    /* if(pCluster->GetNCaloHits() > 300) //Test de split propre avec ajustement sur range basse de la quadratique classique et quad classique sur hautes energies + chevauchement et seuil a 500
    {
      m_energyConstantParameters.push_back(0.0698009); //Meme parametres que pour le Quad_test_2, mais avec le terme linéaire d'alpha boosté, Quad_test_3, Tres bon en linearite mais moins en résolution, J'AI GARDE LUI POUR LES PLOTS
      m_energyConstantParameters.push_back(-9.08617e-05);
      m_energyConstantParameters.push_back(5.24263e-08);
      m_energyConstantParameters.push_back(0.0352866);
      m_energyConstantParameters.push_back(0.000139652);
      m_energyConstantParameters.push_back(-7.83021e-08);
      m_energyConstantParameters.push_back(2.68496e-15);
      m_energyConstantParameters.push_back(0.000885865);
      m_energyConstantParameters.push_back(-5.023e-07);
    }
    else
    {
      m_energyConstantParameters.push_back(0.0644737); //Parametres fit sur Ntot < 600
      m_energyConstantParameters.push_back(-0.000105861);
      m_energyConstantParameters.push_back(7.19378e-08);
      m_energyConstantParameters.push_back(0.0720974);
      m_energyConstantParameters.push_back(8.3249e-05);
      m_energyConstantParameters.push_back(-8.67671e-08);
      m_energyConstantParameters.push_back(0.0106789);
      m_energyConstantParameters.push_back(0.000895708);
      m_energyConstantParameters.push_back(-5.02596e-07);
    } */

    /* if(NHadronicHit < 400) //Test de split propre avec ajustement sur les deux ranges pour Nhcal = 400 -> TRES BON
    {
      m_energyConstantParameters.push_back(0.0772817); //Fit pour Nhcal < 400 
      m_energyConstantParameters.push_back(-0.000201997);
      m_energyConstantParameters.push_back(2.75701e-07);
      m_energyConstantParameters.push_back(0.0717378);
      m_energyConstantParameters.push_back(8.39357e-05);
      m_energyConstantParameters.push_back(-1.30498e-07);
      m_energyConstantParameters.push_back(9.50033e-11);
      m_energyConstantParameters.push_back(0.000751526);
      m_energyConstantParameters.push_back(-1.67637e-07);
    }
    else
    {
      m_energyConstantParameters.push_back(0.0736482); //Fit pour Nhcal > 400
      m_energyConstantParameters.push_back(-9.90976e-05);
      m_energyConstantParameters.push_back(5.20349e-08);
      m_energyConstantParameters.push_back(9.9994e-11);
      m_energyConstantParameters.push_back(0.000196941);
      m_energyConstantParameters.push_back(-9.85922e-08);
      m_energyConstantParameters.push_back(9.95273e-11);
      m_energyConstantParameters.push_back(0.000891664);
      m_energyConstantParameters.push_back(-5.10375e-07);
    } */

    if(NHadronicHit <= 200) //Test de split propre avec ajustement sur les deux ranges pour Nhcal = 200 
    {
      m_energyConstantParameters.push_back(0.0945208); //Fit pour Nhcal <= 200
      m_energyConstantParameters.push_back(-0.000555553);
      m_energyConstantParameters.push_back(1.72828e-06);
      m_energyConstantParameters.push_back(0.122122);
      m_energyConstantParameters.push_back(-0.000546102);
      m_energyConstantParameters.push_back(1.69719e-06);
      m_energyConstantParameters.push_back(0.168558);
      m_energyConstantParameters.push_back(-0.00104433);
      m_energyConstantParameters.push_back(3.94122e-06);
    }
    else
    {
      m_energyConstantParameters.push_back(0.069034); //Fit pour Nhcal > 200
      m_energyConstantParameters.push_back(-9.13475e-05);
      m_energyConstantParameters.push_back(4.89263e-08);
      m_energyConstantParameters.push_back(0.0300912);
      m_energyConstantParameters.push_back(0.000143239);
      m_energyConstantParameters.push_back(-7.64067e-08);
      m_energyConstantParameters.push_back(9.86059e-11);
      m_energyConstantParameters.push_back(0.000882258);
      m_energyConstantParameters.push_back(-4.99842e-07);
    }

    /* m_energyConstantParameters.push_back(0.123637) //Parameters from calibration with correction taken in consideration;
    m_energyConstantParameters.push_back(-0.000238066);
    m_energyConstantParameters.push_back(1.21713e-07);
    m_energyConstantParameters.push_back(-0.0841211);
    m_energyConstantParameters.push_back(0.000443898);
    m_energyConstantParameters.push_back(-2.2225e-07);
    m_energyConstantParameters.push_back(-0.231437);
    m_energyConstantParameters.push_back(0.0014362);
    m_energyConstantParameters.push_back(-7.82703e-07);
 */
   /*  m_energyConstantParameters.push_back(0.140782); //Parameters from calibration without correction taken in consideration
    m_energyConstantParameters.push_back(-0.000315942);
    m_energyConstantParameters.push_back(1.84721e-07);
    m_energyConstantParameters.push_back(-0.0725249);
    m_energyConstantParameters.push_back(0.000528799);
    m_energyConstantParameters.push_back(-2.97119e-07);
    m_energyConstantParameters.push_back(-0.348419);
    m_energyConstantParameters.push_back(0.00202073);
    m_energyConstantParameters.push_back(-1.2337e-06); */

    /* m_energyConstantParameters.push_back(0.0664495); // Alpha1 //Parameters determined with angular constraints and no angle correction, Graphiques_angular_cut
    m_energyConstantParameters.push_back(-0.000110195); // Alpha2
    m_energyConstantParameters.push_back(5.81977e-08); // Alpha3
    m_energyConstantParameters.push_back(0.0615288); // Beta1
    m_energyConstantParameters.push_back(0.000131731); // Beta2
    m_energyConstantParameters.push_back(-4.92238e-08); // Beta3
    m_energyConstantParameters.push_back(-0.0263636); // Gamma1
    m_energyConstantParameters.push_back(0.00111133); // Gamma2
    m_energyConstantParameters.push_back(-6.6486e-07); // Gamma3 */

    /* m_energyConstantParameters.push_back(0.0647539);     // Alpha1 //Parameters determined with angular constraints and angle correction, Graphiques_angular_cut_corrected
    m_energyConstantParameters.push_back(-0.000104734);  // Alpha2
    m_energyConstantParameters.push_back(5.18457e-08);   // Alpha3
    m_energyConstantParameters.push_back(0.0401326);     // Beta1
    m_energyConstantParameters.push_back(0.000166079);   // Beta2
    m_energyConstantParameters.push_back(-6.88591e-08);  // Beta3
    m_energyConstantParameters.push_back(-0.0159042);    // Gamma1
    m_energyConstantParameters.push_back(0.000927328);   // Gamma2
    m_energyConstantParameters.push_back(-5.23047e-07);  // Gamma3 */

    /* m_energyConstantParameters.push_back(0.0640197);     // Alpha1 //Parameters determined with angular constraints + positive gamma3 + angle correction
    m_energyConstantParameters.push_back(-0.000100338);  // Alpha2
    m_energyConstantParameters.push_back(4.60571e-08);   // Alpha3
    m_energyConstantParameters.push_back(-0.0424538);     // Beta1
    m_energyConstantParameters.push_back(0.000412076);   // Beta2
    m_energyConstantParameters.push_back(-2.12832e-07);  // Beta3
    m_energyConstantParameters.push_back(0.283102);    // Gamma1
    m_energyConstantParameters.push_back(6.6085e-05);   // Gamma2
    m_energyConstantParameters.push_back(5.67304e-19);  // Gamma3 */

    /* m_energyConstantParameters.push_back(0.0428963);    // Alpha1 //Limitations sur l'angle du KLong + sans correction angulaire + gamma3 forcé positif + gamma1 forcé négatif + beta3 forcé positif 
    m_energyConstantParameters.push_back(-2.14713e-05); // Alpha2
    m_energyConstantParameters.push_back(-8.54959e-09); // Alpha3
    m_energyConstantParameters.push_back(0.0663658);    // Beta1
    m_energyConstantParameters.push_back(8.36892e-05);  // Beta2
    m_energyConstantParameters.push_back(4.49254e-17);  // Beta3
    m_energyConstantParameters.push_back(0.283198);     // Gamma1
    m_energyConstantParameters.push_back(0.000128254);  // Gamma2
    m_energyConstantParameters.push_back(7.88059e-18);  // Gamma3 */

    /* m_energyConstantParameters.push_back(0.0533058);    // Alpha1 //limitations sur l'angle du KLong + sans correction angulaire + gamma3 forcé positif + beta1 > 0.09 + fonction classique + weight 
    m_energyConstantParameters.push_back(-7.21011e-05); // Alpha2
    m_energyConstantParameters.push_back(3.05851e-08); // Alpha3
    m_energyConstantParameters.push_back(0.0306685);    // Beta1
    m_energyConstantParameters.push_back(0.000274982);  // Beta2
    m_energyConstantParameters.push_back(-1.49925e-07);  // Beta3
    m_energyConstantParameters.push_back(0.26819);     // Gamma1
    m_energyConstantParameters.push_back(0.000138869);  // Gamma2
    m_energyConstantParameters.push_back(2.02263e-11);  // Gamma3 */

    /* m_energyConstantParameters.push_back(0.060967);    // Alpha1 //same as before with *2 in weight 
    m_energyConstantParameters.push_back(-9.23748e-05); // Alpha2
    m_energyConstantParameters.push_back(4.34054e-08); // Alpha3
    m_energyConstantParameters.push_back(0.000168485);    // Beta1
    m_energyConstantParameters.push_back(0.000354545);  // Beta2
    m_energyConstantParameters.push_back(-2.01028e-07);  // Beta3
    m_energyConstantParameters.push_back(0.260893);     // Gamma1
    m_energyConstantParameters.push_back(0.000150581);  // Gamma2
    m_energyConstantParameters.push_back(1.22652e-11);  // Gamma3 */

    /* m_energyConstantParameters.push_back(-0.4904115978);    // Alpha1 //GSL 9*9 v1 fonctionne pas 
    m_energyConstantParameters.push_back(0.0008830129007); // Alpha2
    m_energyConstantParameters.push_back(1.075411858e-07); // Alpha3
    m_energyConstantParameters.push_back(2.254145042);    // Beta1
    m_energyConstantParameters.push_back(-0.003419767951);  // Beta2
    m_energyConstantParameters.push_back(-1.575046818e-06);  // Beta3
    m_energyConstantParameters.push_back(-0.5030654629);     // Gamma1
    m_energyConstantParameters.push_back(0.001537785369);  // Gamma2
    m_energyConstantParameters.push_back(2.430949974e-06);  // Gamma3 */

    /* m_energyConstantParameters.push_back(0.0664563);    // Alpha1 //GSL 9*9 + Chi2 Lot 1 Good
    m_energyConstantParameters.push_back(-0.000110648); // Alpha2
    m_energyConstantParameters.push_back(5.87115e-08); // Alpha3
    m_energyConstantParameters.push_back(0.0637337);    // Beta1
    m_energyConstantParameters.push_back(0.000127242);  // Beta2
    m_energyConstantParameters.push_back(-4.72867e-08);  // Beta3
    m_energyConstantParameters.push_back(-0.0484322);     // Gamma1
    m_energyConstantParameters.push_back(0.00115586);  // Gamma2
    m_energyConstantParameters.push_back(-6.87056e-07);  // Gamma3 */

    /* m_energyConstantParameters.push_back(0.05825);    // Alpha1 //GSL 9*9 contraint + chi2 + noweight on chi2
    m_energyConstantParameters.push_back(-0.000111926); // Alpha2
    m_energyConstantParameters.push_back(7.613e-08); // Alpha3
    m_energyConstantParameters.push_back(0.0971564);    // Beta1
    m_energyConstantParameters.push_back(8.85125e-05);  // Beta2
    m_energyConstantParameters.push_back(-6.5882e-08);  // Beta3
    m_energyConstantParameters.push_back(0.063609);     // Gamma1
    m_energyConstantParameters.push_back(0.00118339);  // Gamma2
    m_energyConstantParameters.push_back(-7.83963e-07);  // Gamma3 */

    /* m_energyConstantParameters.push_back(-2.486999596);    // Alpha1 //GSL 6*6 -> doesnt work
    m_energyConstantParameters.push_back(0.005609951035); // Alpha2
    m_energyConstantParameters.push_back(10.44832247);    // Beta1
    m_energyConstantParameters.push_back(-0.02359578537);  // Beta2
    m_energyConstantParameters.push_back(-2.700219853);     // Gamma1
    m_energyConstantParameters.push_back(0.008447299643);  // Gamma2 */

    // Quadratic correction
    const float alpha(m_energyConstantParameters.at(0) + m_energyConstantParameters.at(1)*NHadronicHit + m_energyConstantParameters.at(2)*NHadronicHit*NHadronicHit);
    const float beta(m_energyConstantParameters.at(3) + m_energyConstantParameters.at(4)*NHadronicHit + m_energyConstantParameters.at(5)*NHadronicHit*NHadronicHit);
    const float gamma(m_energyConstantParameters.at(6) + m_energyConstantParameters.at(7)*NHadronicHit + m_energyConstantParameters.at(8)*NHadronicHit*NHadronicHit);
    const float hadEnergy(NHadronicHit1*alpha + NHadronicHit2*beta + NHadronicHit3*gamma);



    //Linear correction
   /*  const float alpha(m_energyConstantParameters.at(0) + m_energyConstantParameters.at(1)*NHadronicHit);
    const float beta(m_energyConstantParameters.at(2) + m_energyConstantParameters.at(3)*NHadronicHit);
    const float gamma(m_energyConstantParameters.at(4) + m_energyConstantParameters.at(5)*NHadronicHit);
    const float hadEnergy(NHadronicHit1*alpha + NHadronicHit2*beta + NHadronicHit3*gamma); */

    /* if(m_sdhcalThresholds.at(0) != 1) //Test if we use semidigital thresholds
    {
      const float hadEnergy(NHadronicHit1*m_sdhcalThresholds.at(0) + NHadronicHit2*m_sdhcalThresholds.at(1) + NHadronicHit3*m_sdhcalThresholds.at(2)); //New barrel hadronic energy
      correctedEnergy += hadEnergy; //Compute the corrected energy
    }
    else
    { */
      //const float hadEnergy(NHadronicHit1*0.0367023 + NHadronicHit2*0.0745279 + NHadronicHit3*0.363042); //Initial parameters corresponding to the Energy factors
      //const float hadEnergy(NHadronicHit1*0.0433771 + NHadronicHit2*0.088424 + NHadronicHit3*0.457353); //Parameters by Remi in his thesis
      //const float hadEnergy(NHadronicHit1*0.0383865 + NHadronicHit2*0.0637516 + NHadronicHit3*0.295323); //Parameters from TP script
      //const float hadEnergy(NHadronicHit1*0.5820827502 + NHadronicHit2*(-2.361240401) + NHadronicHit3*1.743809464); //Try GSL 10,30,80GeV linear
      //const float hadEnergy(0.480722*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, linear
      //float hadEnergy(1.77366 + 0.33832*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000868032*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde     
      //float hadEnergy(1.46699 + 0.374448*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000963967*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde sans correction     
      //float hadEnergy(1.77366 + 0.32832*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000828032*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde, test 2

      //float hadEnergy(1.77366 + 0.32832*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000848032*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde, TEST A FAIRE


      //float hadEnergy(1.67366 + 0.327533*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.0008202397*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde, test 3 good

      //float hadEnergy(1.77366 + 0.33832*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000868032*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.0250775*(NHadronicHit2-0.273174*NHadronicHit1) - 0.169744*(NHadronicHit3 - 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde, termes supplementaires chi2

      //float hadEnergy(1.67366 + 0.327533*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.0008202397*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.0262739*(NHadronicHit2-0.273174*NHadronicHit1) - 0.156396*(NHadronicHit3 - 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde, test 3, termes supplémentaires
      
      //float hadEnergy(2.00455 + 0.330887*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000838992*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde, condition sur Nhit > 20    

      //correctedEnergy += hadEnergy; //Compute the corrected energy

      //float hadEnergy(1.77366 + 0.32832*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000868032*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde     

      //float hadEnergy(1.77366 + 0.32832*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.0008202397*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) - 0.0094602*(NHadronicHit2-0.273174*NHadronicHit1) - 0.2378*(NHadronicHit3 - 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde, termes supplementaires chi2 sans contrainte sur angle

      //float hadEnergy(1.67366 + 0.33832*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000848032*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde, test 4

      //const float hadEnergy(1.02792 + 0.3901376*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000676844*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde dans le barrel uniquement, test 5
      
      //const float hadEnergy(0.421656*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.00063991*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde dans le barrel uniquement sans terme constant

//const float hadEnergy(0.626581 + 0.37609*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.00049874*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde dans le barrel uniquement et correction en phi videau, test 6, fonctionne

//const float hadEnergy(0.7 + 0.37609*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.00049874*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde dans le barrel uniquement et correction en phi videau, test 7, fonctionne tres bien, le meilleur lot avec cette methode pour le moment

//const float hadEnergy(0.957621 + 0.419409*(NHadronicHit3 + 0.185099 *(NHadronicHit1*0.277335 + NHadronicHit2)) + 0.000774264*(NHadronicHit3 + 0.185099 *(NHadronicHit1*0.277335 + NHadronicHit2))*(NHadronicHit3 + 0.185099 *(NHadronicHit1*0.277335 + NHadronicHit2))); //Valeurs avec nouveaux fichiers de calibration en fixdirection et avec NTilde, test1, not good
      
//const float hadEnergy(2.99859 + 0.583219*(NHadronicHit3 + 0.000163878*(NHadronicHit2 + NHadronicHit1*NHadronicHit1*1.79221*1e-05 + NHadronicHit1*0.257491 - 1.23117)*(NHadronicHit2 + NHadronicHit1*NHadronicHit1*1.79221*1e-05 + NHadronicHit1*0.257491 - 1.23117) + 0.0856896*(NHadronicHit2 + NHadronicHit1*NHadronicHit1*1.79221*1e-05 + NHadronicHit1*0.257491 - 1.23117) - 2.6244) ); //Valeurs avec nouveaux fichiers de calibration en fixdirection et avec NTilde en linéaire mais les termes internes en quadratique, test1, not good

//const float hadEnergy(1.23471 + 0.402872*(NHadronicHit3 + 0.181227 *(NHadronicHit1*0.274229 + NHadronicHit2)) + 0.000510828*(NHadronicHit3 + 0.181227 *(NHadronicHit1*0.274229 + NHadronicHit2))*(NHadronicHit3 + 0.181227 *(NHadronicHit1*0.274229 + NHadronicHit2))); //Valeurs avec nouveaux fichiers de calibration en fixdirection et avec NTilde + Calibration Phi stave v1

//const float hadEnergy(1.22901 + 0.393363*(NHadronicHit3 + 0.188526 *(NHadronicHit1*0.274229 + NHadronicHit2) - 1.93553e-05*( NHadronicHit1*0.274229 + NHadronicHit2 )*( NHadronicHit1*0.274229 + NHadronicHit2 )) + 0.000584061*(NHadronicHit3 + 0.188526 *(NHadronicHit1*0.274229 + NHadronicHit2) - 1.93553e-05*( NHadronicHit1*0.274229 + NHadronicHit2 )*( NHadronicHit1*0.274229 + NHadronicHit2 ))*(NHadronicHit3 + 0.188526 *(NHadronicHit1*0.274229 + NHadronicHit2) - 1.93553e-05*( NHadronicHit1*0.274229 + NHadronicHit2 )*( NHadronicHit1*0.274229 + NHadronicHit2 ))); //Valeurs avec nouveaux fichiers de calibration en fixdirection et avec NTilde + Calibration Phi stave + fit quadratique N3

//const float hadEnergy(1.23471 + 0.39920845*(NHadronicHit3 + 0.181227 *(NHadronicHit1*0.274229 + NHadronicHit2)) + 0.00049228*(NHadronicHit3 + 0.181227 *(NHadronicHit1*0.274229 + NHadronicHit2))*(NHadronicHit3 + 0.181227 *(NHadronicHit1*0.274229 + NHadronicHit2))); //Valeurs avec nouveaux fichiers de calibration en fixdirection et avec NTilde + Calibration Phi stave + baissées à la main


//const float hadEnergy(3.5612 + 0.543915*( NHadronicHit3 + 0.000116323*(NHadronicHit2 + NHadronicHit1*NHadronicHit1*1.66646*1e-05 + NHadronicHit1*0.256779 - 1.30443)*(NHadronicHit2 + NHadronicHit1*NHadronicHit1*1.66646*1e-05 + NHadronicHit1*0.256779 - 1.30443) + 0.0855094*(NHadronicHit2 + NHadronicHit1*NHadronicHit1*1.66646*1e-05 + NHadronicHit1*0.256779 - 1.30443) - 2.67001 ) ); //Valeurs avec nouveaux fichiers de calibration en fixdirection et avec NTilde en linéaire mais les termes internes en quadratique, test2, not good at all
     
//const float hadEnergy(8.95525e-05*(NHadronicHit3 +  2.93836e-05*NHadronicHit1*NHadronicHit1 + 0.066136*NHadronicHit1 - 1.77325 + 0.00032858*NHadronicHit2*NHadronicHit2 + 0.262724*NHadronicHit2 - 1.51835)*(NHadronicHit3 +  2.93836e-05*NHadronicHit1*NHadronicHit1 + 0.066136*NHadronicHit1 - 1.77325 + 0.00032858*NHadronicHit2*NHadronicHit2 + 0.262724*NHadronicHit2 - 1.51835) + 0.327704*(NHadronicHit3 +  2.93836e-05*NHadronicHit1*NHadronicHit1 + 0.066136*NHadronicHit1 - 1.77325 + 0.00032858*NHadronicHit2*NHadronicHit2 + 0.262724*NHadronicHit2 - 1.51835) + 2.03222); //Nouvelle formule avec NTilde basé uniquement sur des relations avec N3

//const float hadEnergy(1.2894 + 0.415109*(NHadronicHit3 + 0.171862 *(NHadronicHit1*0.272315 + NHadronicHit2)) + 0.000527906*(NHadronicHit3 + 0.171862 *(NHadronicHit1*0.272315 + NHadronicHit2))*(NHadronicHit3 + 0.171862 *(NHadronicHit1*0.272315 + NHadronicHit2))); //Valeurs avec nouveaux fichiers de calibration en fixdirection et avec NTilde + Calibration Phi stave + coeffs via analyse en composante principale

//const float hadEnergy(0.3298*(4.73081e-05*NHadronicHit1*NHadronicHit1 + 0.0668336*NHadronicHit1 +  0.000492912*NHadronicHit2*NHadronicHit2 + 0.264927*NHadronicHit2 + 0.000764138*NHadronicHit3*NHadronicHit3 + 0.839078*NHadronicHit3 + 3.00868)); //Test de la combinaison des trois formules (N1, N2, N3) multipliées par un tier

//const float hadEnergy(0.661408*(NHadronicHit3 + 0.115332*(NHadronicHit1*0.289489 + NHadronicHit2)) + 0.738055); //Ntilde lineaire, FTFP_BERT, displaced Tesla

//NTILDE A PARTIR DES EVENTS UDS POUR COEFF ET NTILDE
//const float hadEnergy(4.11697 + 0.865048*(NHadronicHit3 + 0.113813 *(NHadronicHit1*0.247633 + NHadronicHit2)) - 0.000501047*(NHadronicHit3 + 0.113813 *(NHadronicHit1*0.247633 + NHadronicHit2))*(NHadronicHit3 + 0.113813 *(NHadronicHit1*0.247633 + NHadronicHit2))); 

//Based on machine learning with sklearn, quadratic
//const float hadEnergy(0.044191*NHadronicHit1 + 0.071432*NHadronicHit2 + 0.300506*NHadronicHit3 -0.000003*NHadronicHit1*NHadronicHit1 + 0.000086*NHadronicHit1*NHadronicHit2 -0.000552*NHadronicHit1*NHadronicHit3 -0.000089*NHadronicHit2*NHadronicHit2 -0.000007*NHadronicHit2*NHadronicHit3 + 0.003557*NHadronicHit3*NHadronicHit3);

//Based on ML with sklearn, degree 3
//const float hadEnergy(0.067555*NHadronicHit1 + 0.055146*NHadronicHit2 -0.073022*NHadronicHit3 + 0.000002*NHadronicHit1*NHadronicHit1 -0.000140*NHadronicHit1*NHadronicHit2 + -0.001114*NHadronicHit1*NHadronicHit3 + 0.000348*NHadronicHit2*NHadronicHit2 + 0.001752*NHadronicHit2*NHadronicHit3 + 0.012622*NHadronicHit3*NHadronicHit3 + 0.000002*NHadronicHit1*NHadronicHit2*NHadronicHit3 -0.000002*NHadronicHit1*NHadronicHit3*NHadronicHit3 -0.000006*NHadronicHit2*NHadronicHit2*NHadronicHit3 -0.000012*NHadronicHit2*NHadronicHit3*NHadronicHit3 -0.000035*NHadronicHit3*NHadronicHit3*NHadronicHit3);
      
//NTILDE avec coeff entre hits pris sur les uds. Pas mal   
//const float hadEnergy(0.7 + 0.37609*(NHadronicHit3 + 0.115178 *(NHadronicHit1*0.248168  + NHadronicHit2)) + 0.00049874*(NHadronicHit3 + 0.115178 *(NHadronicHit1*0.248168  + NHadronicHit2))*(NHadronicHit3 + 0.115178 *(NHadronicHit1*0.248168  + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde dans le barrel uniquement et correction en phi videau, test 7, fonctionne tres bien, le meilleur lot avec cette methode pour le moment

//NTilde avec tous les coeffs determines par minimisation chi2
//const float hadEnergy(1.33453 + 0.322512*(NHadronicHit3 + 0.244866 *(NHadronicHit1*0.401233  + NHadronicHit2)) + 4.53379e-05*(NHadronicHit3 + 0.244866 *(NHadronicHit1*0.401233  + NHadronicHit2))*(NHadronicHit3 + 0.244866 *(NHadronicHit1*0.401233  + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde dans le barrel uniquement et correction en phi videau, test 7, fonctionne tres bien, le meilleur lot avec cette methode pour le moment


//ML degré 3 en split pour Ntot = 400
/* float hadEnergy;

if(pCluster->GetNCaloHits() < 400) 
{
  hadEnergy = 0.055274*NHadronicHit1 + 0.112028*NHadronicHit2 + 0.490528*NHadronicHit3 + 0.000120*NHadronicHit1*NHadronicHit1 - 0.002118*NHadronicHit1*NHadronicHit2 - 0.002405*NHadronicHit1*NHadronicHit3 + 0.004133*NHadronicHit2*NHadronicHit2 - 0.004745*NHadronicHit2*NHadronicHit3 + 0.014478*NHadronicHit3*NHadronicHit3 - 0.000001*NHadronicHit1*NHadronicHit1*NHadronicHit1 + 0.000013*NHadronicHit1*NHadronicHit1*NHadronicHit2 + 0.000002*NHadronicHit1*NHadronicHit1*NHadronicHit3 - 0.000034*NHadronicHit1*NHadronicHit2*NHadronicHit2 + 0.000001*NHadronicHit1*NHadronicHit2*NHadronicHit3 - 0.000008*NHadronicHit1*NHadronicHit3*NHadronicHit3 + 0.000022*NHadronicHit2*NHadronicHit2*NHadronicHit2 + 0.000043*NHadronicHit2*NHadronicHit2*NHadronicHit3 - 0.000024*NHadronicHit2*NHadronicHit3*NHadronicHit3 - 0.000026*NHadronicHit3*NHadronicHit3*NHadronicHit3;
}
else
{
  hadEnergy = 0.076798*NHadronicHit1 + 0.038953*NHadronicHit2 - 0.190943*NHadronicHit3 - 0.000039*NHadronicHit1*NHadronicHit1 + 0.000024*NHadronicHit1*NHadronicHit2 - 0.000830*NHadronicHit1*NHadronicHit3 + 0.000131*NHadronicHit2*NHadronicHit2 + 0.001773*NHadronicHit2*NHadronicHit3 + 0.012946*NHadronicHit3*NHadronicHit3 + 0.000002*NHadronicHit1*NHadronicHit2*NHadronicHit3 - 0.000003*NHadronicHit1*NHadronicHit3*NHadronicHit3 - 0.000004*NHadronicHit2*NHadronicHit2*NHadronicHit3 - 0.000013*NHadronicHit2*NHadronicHit3*NHadronicHit3 - 0.000033*NHadronicHit3*NHadronicHit3*NHadronicHit3;
} */

correctedEnergy = lumiHCALEnergy + emEnergy + hadEnergy;

/* Minimizer is Linear / Migrad
Chi2                  	=  	11.9267
NDf                   	=       	83
p0                    	=  	1.23471   +/-   0.155893    
p1                    	= 	0.402872   +/-   0.00366355  
p2                    	=  0.000510828   +/-   1.8548e-05  */



      //std::cout << "CORRECTED FINAL : " << correctedEnergy << std::endl;
  //}

/* double coeffN1 = -0.229213;
double coeffN2 = -0.003595;
double coeffN3 = 0.415352;
double coeffNhit = 0.182544;
double coeffN1_sq = 0.000537;
double coeffN1_N2 = 0.000184;
double coeffN1_N3 = -0.001247;
double coeffN1_Nhit = -0.000526;
double coeffN2_sq = -0.000251;
double coeffN2_N3 = 0.000181;
double coeffN2_Nhit = 0.000114;
double coeffN3_sq = 0.001567;
double coeffN3_Nhit = 0.000501;
double coeffNhit_sq = 0.000088;
 //scikit 60% entrainement quadratique

    double hadEnergy = 0;
    hadEnergy += coeffN1 * NHadronicHit1;
    hadEnergy += coeffN2 * NHadronicHit2;
    hadEnergy += coeffN3 * NHadronicHit3;
    hadEnergy += coeffNhit * NHadronicHit;
    hadEnergy += coeffN1_sq * NHadronicHit1 * NHadronicHit1;
    hadEnergy += coeffN1_N2 * NHadronicHit1 * NHadronicHit2;
    hadEnergy += coeffN1_N3 * NHadronicHit1 * NHadronicHit3;
    hadEnergy += coeffN1_Nhit * NHadronicHit1 * NHadronicHit;
    hadEnergy += coeffN2_sq * NHadronicHit2 * NHadronicHit2;
    hadEnergy += coeffN2_N3 * NHadronicHit2 * NHadronicHit3;
    hadEnergy += coeffN2_Nhit * NHadronicHit2 * NHadronicHit;
    hadEnergy += coeffN3_sq * NHadronicHit3 * NHadronicHit3;
    hadEnergy += coeffN3_Nhit * NHadronicHit3 * NHadronicHit;
    hadEnergy += coeffNhit_sq * NHadronicHit * NHadronicHit;
    correctedEnergy += hadEnergy; //Compute the corrected energy
     */

    

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float AngleCorrectionPlugin::GetCosTheta(const pandora::Cluster *const pCluster) const
  {
    pandora::CartesianVector centroid(0.f, 0.f, 0.f);
    PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));

    //std::cout << "CENTROID : " << centroid << std::endl;

    return fabs(centroid.GetCosOpeningAngle(pandora::CartesianVector(0.f, 0.f, 1.f)));
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float AngleCorrectionPlugin::GetCosPhi(const pandora::Cluster *const pCluster) const
  {
    pandora::CartesianVector centroid(0.f, 0.f, 0.f);
    pandora::CartesianVector zAxis(0.f, 0.f, 1.f);
  
    PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));
    pandora::CartesianVector projectedCentroid(zAxis.GetCrossProduct(centroid.GetCrossProduct(zAxis))); //Project the postion vector of the cluster in the XY-plane 
    float phiAngle = projectedCentroid.GetOpeningAngle(pandora::CartesianVector(0.f, 1.f, 0.f)); //Returns an angle between 0 and PI in rad
    while(phiAngle>M_PI_4/2) //Substract PI/4 until the angle is between -PI/8 and PI/8 rad
    {
        phiAngle-=M_PI_4;
    }

    return fabs(std::cos(phiAngle)); 
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float AngleCorrectionPlugin::GetCorrectedHitNumber(int nHit, float cosOrSinAngle) const
  {
	  //std::cout << "nHit: " << nHit << ", cosTheta: " << cosTheta << std::endl;
    //std::cout << "Nouveau nombre de hits : " << nHit * ( (1. / cosOrSinAngle) - 1 ) << std::endl;
    return nHit * ( (1. / cosOrSinAngle) - 1 );
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode AngleCorrectionPlugin::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "LowEnergyCut", m_lowEnergyCut));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "UseDigi", m_useDigi));

    return pandora::STATUS_CODE_SUCCESS;
  }

//------------------------------------------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------------------------------------------  

CleanCluster::CleanCluster() :
    m_minCleanHitEnergy(0.5f),
    m_minCleanHitEnergyFraction(0.01f),
    m_minCleanCorrectedHitEnergy(0.1f)
{
}

//------------------------------------------------------------------------------------------------------------------------------------------

pandora::StatusCode CleanCluster::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedHadronicEnergy) const
{
    const unsigned int firstPseudoLayer(this->GetPandora().GetPlugins()->GetPseudoLayerPlugin()->GetPseudoLayerAtIp());

    const float clusterHadronicEnergy(pCluster->GetHadronicEnergy());

    if (std::fabs(clusterHadronicEnergy) < std::numeric_limits<float>::epsilon())
        throw pandora::StatusCodeException(pandora::STATUS_CODE_FAILURE);

    bool isFineGranularity(true);
    const pandora::OrderedCaloHitList &orderedCaloHitList(pCluster->GetOrderedCaloHitList());

    // Loop over all constituent inner layer fine granularity hits, looking for anomalies
    for (pandora::OrderedCaloHitList::const_iterator layerIter = orderedCaloHitList.begin(), layerIterEnd = orderedCaloHitList.end();
        (layerIter != layerIterEnd) && isFineGranularity; ++layerIter)
    {
        const unsigned int pseudoLayer(layerIter->first);

        for (pandora::CaloHitList::const_iterator hitIter = layerIter->second->begin(), hitIterEnd = layerIter->second->end();
            hitIter != hitIterEnd; ++hitIter)
        {
            const pandora::CaloHit *const pCaloHit = *hitIter;

            if (this->GetPandora().GetGeometry()->GetHitTypeGranularity((*hitIter)->GetHitType()) > pandora::FINE)
            {
                isFineGranularity = false;
                break;
            }

            const float hitHadronicEnergy(pCaloHit->GetHadronicEnergy());

            if ((hitHadronicEnergy > m_minCleanHitEnergy) && (hitHadronicEnergy / clusterHadronicEnergy > m_minCleanHitEnergyFraction))
            {
                // Calculate new energy from surrounding layers
                float energyInPreviousLayer(0.);

                if (pseudoLayer > firstPseudoLayer)
                    energyInPreviousLayer = this->GetHadronicEnergyInLayer(orderedCaloHitList, pseudoLayer - 1);

                float energyInNextLayer(0.);

                if (pseudoLayer < std::numeric_limits<unsigned int>::max())
                    energyInNextLayer = this->GetHadronicEnergyInLayer(orderedCaloHitList, pseudoLayer + 1);

                const float energyInCurrentLayer = this->GetHadronicEnergyInLayer(orderedCaloHitList, pseudoLayer);

                // Calculate new energy estimate for hit and update cluster best energy estimate
                float energyInAdjacentLayers(energyInPreviousLayer + energyInNextLayer);

                if (pseudoLayer > firstPseudoLayer)
                    energyInAdjacentLayers /= 2.f;

                float newHitHadronicEnergy(energyInAdjacentLayers - energyInCurrentLayer + hitHadronicEnergy);
                newHitHadronicEnergy = std::max(newHitHadronicEnergy, m_minCleanCorrectedHitEnergy);

                if (newHitHadronicEnergy < hitHadronicEnergy)
                    correctedHadronicEnergy += newHitHadronicEnergy - hitHadronicEnergy;
            }
        }
    }

    return pandora::STATUS_CODE_SUCCESS;
}

//------------------------------------------------------------------------------------------------------------------------------------------

float CleanCluster::GetHadronicEnergyInLayer(const pandora::OrderedCaloHitList &orderedCaloHitList, const unsigned int pseudoLayer) const
{
	pandora::OrderedCaloHitList::const_iterator iter = orderedCaloHitList.find(pseudoLayer);

    float hadronicEnergy(0.f);

    if (iter != orderedCaloHitList.end())
    {
        for (pandora::CaloHitList::const_iterator hitIter = iter->second->begin(), hitIterEnd = iter->second->end(); hitIter != hitIterEnd; ++hitIter)
        {
            hadronicEnergy += (*hitIter)->GetHadronicEnergy();
        }
    }

    return hadronicEnergy;
}

//------------------------------------------------------------------------------------------------------------------------------------------

pandora::StatusCode CleanCluster::ReadSettings(const pandora::TiXmlHandle xmlHandle)
{
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "MinCleanHitEnergy", m_minCleanHitEnergy));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "MinCleanHitEnergyFraction", m_minCleanHitEnergyFraction));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "MinCleanCorrectedHitEnergy", m_minCleanCorrectedHitEnergy));

    return pandora::STATUS_CODE_SUCCESS;
}

}

