/// \file EnergyCorrectionPlugin.cc
/*
 *
 * EnergyCorrectionPlugin.cc source template automatically generated by a class generator
 * Creation date : mar. nov. 17 2015
 * Updated november 2023 by Tanguy Pasquier
 *
 * This file is part of SDHCALContent libraries.
 * 
 * SDHCALContent is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * SDHCALContent is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SDHCALContent.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */
#include <fstream>
#include "SDHCALPlugins/EnergyCorrectionPlugins.h"
#include "SDHCALHelpers/ClusterHelper.h"

#include "Pandora/AlgorithmHeaders.h"

namespace sdhcal_content
{
  AnalogicEnergyFunction::AnalogicEnergyFunction() :
        m_ecalEnergyType(0),
        m_hcalEnergyType(0),
        m_muonEnergyType(0),
        m_otherEnergyType(0)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode AnalogicEnergyFunction::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    correctedEnergy = 0.f;

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit = *iter;

      const pandora::HitType hitType(pCaloHit->GetHitType());

      const unsigned int energyType(
          (hitType == pandora::ECAL) ? m_ecalEnergyType :
              (hitType == pandora::HCAL) ? m_hcalEnergyType :
                  (hitType == pandora::MUON) ? m_muonEnergyType :
                      m_otherEnergyType);

      switch(energyType)
      {
      case 0:
        correctedEnergy += pCaloHit->GetInputEnergy();
        break;
      case 1:
        correctedEnergy += pCaloHit->GetElectromagneticEnergy();
        break;
      case 2:
        correctedEnergy += pCaloHit->GetHadronicEnergy();
        break;
      default:
        correctedEnergy += pCaloHit->GetInputEnergy();
        break;
      }
    }

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode AnalogicEnergyFunction::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    m_ecalEnergyType = 0;
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "EcalEnergyType", m_ecalEnergyType));

    m_hcalEnergyType = 0;
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "HcalEnergyType", m_hcalEnergyType));

    m_muonEnergyType = 0;
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "MuonEnergyType", m_muonEnergyType));

    m_otherEnergyType = 0;
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "OtherEnergyType", m_otherEnergyType));

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  SdhcalQuadraticEnergyFunction::SdhcalQuadraticEnergyFunction()
  {
    m_energyConstantParameters.push_back(0.0385315);
    m_energyConstantParameters.push_back(4.22584e-05);
    m_energyConstantParameters.push_back(-7.54657e-09);
    m_energyConstantParameters.push_back(0.0784297);
    m_energyConstantParameters.push_back(-5.69439e-05);
    m_energyConstantParameters.push_back(-4.95924e-08);
    m_energyConstantParameters.push_back(0.127212);
    m_energyConstantParameters.push_back(4.56414e-05);
    m_energyConstantParameters.push_back(1.41142e-08);

    m_sdhcalThresholds.push_back(1);
    m_sdhcalThresholds.push_back(2);
    m_sdhcalThresholds.push_back(3);
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode SdhcalQuadraticEnergyFunction::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    unsigned int NHadronicHit  = 0;
    unsigned int NHadronicHit1 = 0;
    unsigned int NHadronicHit2 = 0;
    unsigned int NHadronicHit3 = 0;

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    float emEnergy = 0.f;
    float otherEnergy = 0.f;

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit = *iter;

      // Ecal case. Get the calibrated hit energy
      if(pandora::ECAL == pCaloHit->GetHitType())
      {
        emEnergy += pCaloHit->GetElectromagneticEnergy();
        continue;
      }
      // SDHCAL case. Do thresholds counting
      else if(pandora::HCAL == pCaloHit->GetHitType())
      {
        if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          NHadronicHit1++;
        else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          NHadronicHit2++;
        else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          NHadronicHit3++;
        else
        {
          otherEnergy += pCaloHit->GetInputEnergy();
          continue;
        }

        NHadronicHit++;
      }
      // Other hit types ... should never happen
      else
      {
        otherEnergy += pCaloHit->GetInputEnergy();
      }
    }

    std::ofstream outputFile;
    outputFile.open("/scratch/pasquier/other_energy.txt");
    outputFile << otherEnergy << std::endl;
    outputFile.close();


    // estimate of sdhcal energy
    const float alpha(m_energyConstantParameters.at(0) + m_energyConstantParameters.at(1)*NHadronicHit + m_energyConstantParameters.at(2)*NHadronicHit*NHadronicHit);
    const float beta(m_energyConstantParameters.at(3) + m_energyConstantParameters.at(4)*NHadronicHit + m_energyConstantParameters.at(5)*NHadronicHit*NHadronicHit);
    const float gamma(m_energyConstantParameters.at(6) + m_energyConstantParameters.at(7)*NHadronicHit + m_energyConstantParameters.at(8)*NHadronicHit*NHadronicHit);
    const float hadEnergy(NHadronicHit1*alpha + NHadronicHit2*beta + NHadronicHit3*gamma);

    correctedEnergy = emEnergy + hadEnergy + otherEnergy;

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode SdhcalQuadraticEnergyFunction::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    pandora::FloatVector energyConstantParameters;
    pandora::StatusCode statusCode = pandora::XmlHelper::ReadVectorOfValues(xmlHandle,
        "EnergyConstantParameters", energyConstantParameters);

    if(statusCode == pandora::STATUS_CODE_SUCCESS)
    {
      m_energyConstantParameters = energyConstantParameters;
    }
    else if(statusCode != pandora::STATUS_CODE_NOT_FOUND)
    {
      return statusCode;
    }

    if(9 != m_energyConstantParameters.size())
      return pandora::STATUS_CODE_INVALID_PARAMETER;

    pandora::FloatVector sdhcalThresholds;
    statusCode = pandora::XmlHelper::ReadVectorOfValues(xmlHandle,
        "SdhcalThresholds", sdhcalThresholds);

    if(statusCode == pandora::STATUS_CODE_SUCCESS)
    {
      m_sdhcalThresholds = sdhcalThresholds;
    }
    else if(statusCode != pandora::STATUS_CODE_NOT_FOUND)
    {
      return statusCode;
    }

    if(3 != m_sdhcalThresholds.size())
      return pandora::STATUS_CODE_INVALID_PARAMETER;

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  BarrelGapEnergyFunction::BarrelGapEnergyFunction() :
        m_ecalDistanceToGap(10.f),  // 8 mm + 2 mm
        m_hcalDistanceToGap(30.f),  // 20 mm + 10 mm
        m_ecalGapAlpha(0),
        m_ecalGapBeta(0),
        m_hcalGapAlpha(1.5254),
        m_hcalGapBeta(0)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode BarrelGapEnergyFunction::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
	  //std::cout << "BarrelGapEnergyFunction::MakeEnergyCorrections" << std::endl;
    if(m_ecalZGapPositions.empty() && m_hcalZGapPositions.empty())
      return pandora::STATUS_CODE_SUCCESS;

    if(pCluster->GetNCaloHits() == 0)
      return pandora::STATUS_CODE_SUCCESS;

    float ecalGapEnergy(0), hcalGapEnergy(0);

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit(*iter);
      const bool nearbyGap(this->IsNearbyGap(pCaloHit));

      if(!nearbyGap)
        continue;

      if(pCaloHit->GetHitType() == pandora::ECAL)
        ecalGapEnergy += pCaloHit->GetHadronicEnergy();
      else if(pCaloHit->GetHitType() == pandora::HCAL)
        hcalGapEnergy += pCaloHit->GetHadronicEnergy();
    }

    correctedEnergy +=
        m_ecalGapAlpha * ecalGapEnergy + m_ecalGapBeta * ecalGapEnergy * ecalGapEnergy +
        m_hcalGapAlpha * hcalGapEnergy + m_hcalGapBeta * hcalGapEnergy * hcalGapEnergy;

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  bool BarrelGapEnergyFunction::IsNearbyGap(const pandora::CaloHit *const pCaloHit) const
  {
    if(pCaloHit->GetHitRegion() != pandora::BARREL)
      return false;

    if(pCaloHit->GetHitType() != pandora::ECAL && pCaloHit->GetHitType() != pandora::HCAL)
      return false;

    const pandora::FloatVector zGapPositions(pCaloHit->GetHitType() == pandora::ECAL ? m_ecalZGapPositions : m_hcalZGapPositions);
    const float distanceToGap(pCaloHit->GetHitType() == pandora::ECAL ? m_ecalDistanceToGap : m_hcalDistanceToGap);
    const float hitZ(pCaloHit->GetPositionVector().GetZ());

    for(pandora::FloatVector::const_iterator iter = zGapPositions.begin(), endIter = zGapPositions.end() ;
        endIter != iter ; ++iter)
    {
      const float gapZPosition(*iter);

      if( ((hitZ < gapZPosition) && (hitZ > gapZPosition-distanceToGap))
       || ((hitZ > gapZPosition) && (hitZ < gapZPosition+distanceToGap)) )
      {
        return true;
      }
    }

    return false;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode BarrelGapEnergyFunction::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadVectorOfValues(xmlHandle,
        "EcalZGapPositions", m_ecalZGapPositions));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadVectorOfValues(xmlHandle,
        "HcalZGapPositions", m_hcalZGapPositions));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "EcalDistanceToGap", m_ecalDistanceToGap));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "HcalDistanceToGap", m_hcalDistanceToGap));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "EcalGapAlpha", m_ecalGapAlpha));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "EcalGapBeta", m_ecalGapBeta));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "HcalGapAlpha", m_hcalGapAlpha));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "HcalGapBeta", m_hcalGapBeta));

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  ThetaNHitFunction::ThetaNHitFunction() :
       m_lowEnergyCut(3.f)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode ThetaNHitFunction::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    pandora::FloatVector m_sdhcalThresholds; //Vector to store the thresholds used
    if(m_useDigi)
    {
      m_sdhcalThresholds.push_back(1);
      m_sdhcalThresholds.push_back(2);
      m_sdhcalThresholds.push_back(3);
    }
    else 
    {
      m_sdhcalThresholds.push_back(0.0367023);
      m_sdhcalThresholds.push_back(0.0745279);
      m_sdhcalThresholds.push_back(0.363042);
    }
    //unsigned int NHadronicHit = 0;
    unsigned int NHadronicHit1 = 0;
    unsigned int NHadronicHit2 = 0;
    unsigned int NHadronicHit3 = 0;
  
    unsigned int barrelNHadronicHit1 = 0;
    unsigned int barrelNHadronicHit2 = 0;
    unsigned int barrelNHadronicHit3 = 0;

    unsigned int endcapNHadronicHit1 = 0;
    unsigned int endcapNHadronicHit2 = 0; 
    unsigned int endcapNHadronicHit3 = 0; 

    float initialHadronic = 0;

    float emEnergy = 0;

    if(pCluster->GetNCaloHits() == 0)
      return pandora::STATUS_CODE_SUCCESS;

    if(correctedEnergy < m_lowEnergyCut)
      return pandora::STATUS_CODE_SUCCESS;

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    bool noShowerHit(true);

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit(*iter);

      if(pCaloHit->GetHitType() == pandora::ECAL) //Only focus on SDHCAL corrections
      {
        emEnergy += pCaloHit->GetElectromagneticEnergy();
      }

      if(pCaloHit->GetHitType() == pandora::HCAL)
        {
          if(pCaloHit->GetHitRegion() == pandora::BARREL)
          {
            if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              barrelNHadronicHit1++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.0367023;
            }
            else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              barrelNHadronicHit2++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.0745279;
            }
            else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              barrelNHadronicHit3++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.363042;
            }
          }
          else if(pCaloHit->GetHitRegion() == pandora::ENDCAP)
          {
            if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            { 
              endcapNHadronicHit1++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.0367023;
            }
            else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              endcapNHadronicHit2++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.0745279;
            }
            else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              endcapNHadronicHit3++;
              initialHadronic+=pCaloHit->GetInputEnergy();
              //initialHadronic+=0.363042;
            }
          }
          noShowerHit = false;
        }
    }

    if(noShowerHit)
      return pandora::STATUS_CODE_SUCCESS;

    correctedEnergy-=initialHadronic; // Pull the initial energy of the HCAL hits from the total energy to correct

    /* std::cout << "NHadronicHit : " << NHadronicHit << std::endl;
    std::cout << "barrelNHadronicHit1 : " << barrelNHadronicHit1 << std::endl;
    std::cout << "barrelNHadronicHit2 : " << barrelNHadronicHit2 << std::endl;
    std::cout << "barrelNHadronicHit3 : " << barrelNHadronicHit3 << std::endl;

    std::cout << "endcapNHadronicHit1 : " << endcapNHadronicHit1 << std::endl;
    std::cout << "endcapNHadronicHit2 : " << endcapNHadronicHit2 << std::endl;
    std::cout << "endcapNHadronicHit3 : " << endcapNHadronicHit3 << std::endl; */

    //Parameters for geometric theta correction
    const float clusterCosTheta(this->GetCosTheta(pCluster)); //Cos theta for the endcap correction
    const float thetaAngle(std::acos(clusterCosTheta)); //Theta angle
    const float clusterSinTheta(std::sin(thetaAngle)); //Sin theta for the barrel correction

    //Sum the corrected number of hits for each tresholds
    NHadronicHit1 = this->GetCorrectedHitNumber(barrelNHadronicHit1, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit1, clusterCosTheta);
    NHadronicHit2 = this->GetCorrectedHitNumber(barrelNHadronicHit2, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit2, clusterCosTheta);
    NHadronicHit3 = this->GetCorrectedHitNumber(barrelNHadronicHit3, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit3, clusterCosTheta);

    /* //Calculate the corrected total number of hits
    NHadronicHit = NHadronicHit1 + NHadronicHit2 + NHadronicHit3;

    //std::cout << "NHit corrected : " << NHadronicHit << std::endl;

    pandora::FloatVector m_energyConstantParameters;

    m_energyConstantParameters.push_back(0.0385315);
    m_energyConstantParameters.push_back(4.22584e-05);
    m_energyConstantParameters.push_back(-7.54657e-09);
    m_energyConstantParameters.push_back(0.0784297);
    m_energyConstantParameters.push_back(-5.69439e-05);
    m_energyConstantParameters.push_back(-4.95924e-08);
    m_energyConstantParameters.push_back(0.127212);
    m_energyConstantParameters.push_back(4.56414e-05);
    m_energyConstantParameters.push_back(1.41142e-08);

    // Quadratic correction
    const float alpha(m_energyConstantParameters.at(0) + m_energyConstantParameters.at(1)*NHadronicHit + m_energyConstantParameters.at(2)*NHadronicHit*NHadronicHit);
    const float beta(m_energyConstantParameters.at(3) + m_energyConstantParameters.at(4)*NHadronicHit + m_energyConstantParameters.at(5)*NHadronicHit*NHadronicHit);
    const float gamma(m_energyConstantParameters.at(6) + m_energyConstantParameters.at(7)*NHadronicHit + m_energyConstantParameters.at(8)*NHadronicHit*NHadronicHit);
    const float hadEnergy(NHadronicHit1*alpha + NHadronicHit2*beta + NHadronicHit3*gamma); */

    //const float hadEnergy(NHadronicHit1*0.0367023 + NHadronicHit2*0.0745279 + NHadronicHit3*0.363042); //Initial parameters
    //float hadEnergy(1.77366 + 0.33832*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000868032*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde
    float hadEnergy(1.77366 + 0.32832*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2)) + 0.000858032*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))*(NHadronicHit3 + 0.197756 *(NHadronicHit1*0.273174 + NHadronicHit2))); //Nouvelle approche avec moyennes, fit sur moyennes de NTilde, test 3

    //correctedEnergy += hadEnergy; //Compute the corrected energy

    correctedEnergy = emEnergy + hadEnergy;

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float ThetaNHitFunction::GetCosTheta(const pandora::Cluster *const pCluster) const
  {
    pandora::CartesianVector centroid(0.f, 0.f, 0.f);
    PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));

    return fabs(centroid.GetCosOpeningAngle(pandora::CartesianVector(0.f, 0.f, 1.f)));
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float ThetaNHitFunction::GetCorrectedHitNumber(int nHit, float cosTheta) const
  {
	  //std::cout << "nHit: " << nHit << ", cosTheta: " << cosTheta << std::endl;
    return nHit * (1 / (cosTheta));
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode ThetaNHitFunction::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "LowEnergyCut", m_lowEnergyCut));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "UseDigi", m_useDigi));

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  PhiNHitTesla::PhiNHitTesla() :
       m_lowEnergyCut(3.f)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode PhiNHitTesla::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    pandora::FloatVector m_sdhcalThresholds; //Vector to store the thresholds used
    if(m_useDigi)
    {
      m_sdhcalThresholds.push_back(1);
      m_sdhcalThresholds.push_back(2);
      m_sdhcalThresholds.push_back(3);
    }
    else 
    {
      m_sdhcalThresholds.push_back(0.0367023);
      m_sdhcalThresholds.push_back(0.0745279);
      m_sdhcalThresholds.push_back(0.363042);
    }
    
    unsigned int NHadronicHit1 = 0;
    unsigned int NHadronicHit2 = 0;
    unsigned int NHadronicHit3 = 0;
  
    unsigned int barrelNHadronicHit1 = 0;
    unsigned int barrelNHadronicHit2 = 0;
    unsigned int barrelNHadronicHit3 = 0; 

    float initialBarrelHadronic = 0;

    if(pCluster->GetNCaloHits() == 0)
      return pandora::STATUS_CODE_SUCCESS;

    if(correctedEnergy < m_lowEnergyCut)
      return pandora::STATUS_CODE_SUCCESS;

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    bool noShowerHit(true);

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit(*iter);

      if(pCaloHit->GetHitType() == pandora::HCAL)
        {
          if(pCaloHit->GetHitRegion() == pandora::BARREL)
          {
            if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            { 
              barrelNHadronicHit1++;
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.0367023;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }
            }
            else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              barrelNHadronicHit2++;
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.0745279;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }
            }
            else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              barrelNHadronicHit3++;
              
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.363042;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }
            }
          }
          noShowerHit = false;
        }
    }

    if(noShowerHit)
      return pandora::STATUS_CODE_SUCCESS;

    correctedEnergy-=initialBarrelHadronic; // Pull the initial energy of the HCAL hits from the total energy to correct

    /* std::cout << "NHadronicHit : " << NHadronicHit << std::endl;
    std::cout << "barrelNHadronicHit1 : " << barrelNHadronicHit1 << std::endl;
    std::cout << "barrelNHadronicHit2 : " << barrelNHadronicHit2 << std::endl;
    std::cout << "barrelNHadronicHit3 : " << barrelNHadronicHit3 << std::endl; */

    //Parameters for geometric phi correction
    const float clusterCosPhi(this->GetCosPhi(pCluster)); //Cos theta for the endcap correction

    //Sum the corrected number of hits for each tresholds
    NHadronicHit1 = this->GetCorrectedHitNumber(barrelNHadronicHit1, clusterCosPhi);
    NHadronicHit2 = this->GetCorrectedHitNumber(barrelNHadronicHit2, clusterCosPhi);
    NHadronicHit3 = this->GetCorrectedHitNumber(barrelNHadronicHit3, clusterCosPhi);

    const float correctedBarrelEnergy(NHadronicHit1*0.0367023 + NHadronicHit2*0.0745279 + NHadronicHit3*0.363042); //New barrel hadronic energy
    correctedEnergy += correctedBarrelEnergy; //Compute the corrected energy
   
    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float PhiNHitTesla::GetCosPhi(const pandora::Cluster *const pCluster) const
  {
    pandora::CartesianVector centroid(0.f, 0.f, 0.f);
    pandora::CartesianVector zAxis(0.f, 0.f, 1.f);
  
    PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));
    pandora::CartesianVector projectedCentroid(zAxis.GetCrossProduct(centroid.GetCrossProduct(zAxis))); //Project the postion vector of the cluster in the XY-plane 
    float phiAngle = projectedCentroid.GetOpeningAngle(pandora::CartesianVector(0.f, 1.f, 0.f)); //Returns an angle between 0 and PI in rad
    while(phiAngle>M_PI_4/2) //Substract PI/4 until the angle is between -PI/8 and PI/8 rad
    {
        phiAngle-=M_PI_4;
    }

    return fabs(std::cos(phiAngle)); 
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float PhiNHitTesla::GetCorrectedHitNumber(int nHit, float cosPhi) const
  {
	  //std::cout << "nHit: " << nHit << ", cosTheta: " << cosTheta << std::endl;
    return nHit * (1 / (cosPhi));
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode PhiNHitTesla::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "LowEnergyCut", m_lowEnergyCut));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "UseDigi", m_useDigi));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "ThetaBefore", m_thetaBefore));

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  PhiNHitVideau::PhiNHitVideau() :
       m_lowEnergyCut(3.f)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode PhiNHitVideau::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    pandora::FloatVector m_sdhcalThresholds; //Vector to store the thresholds used
    if(m_useDigi)
    {
      m_sdhcalThresholds.push_back(1);
      m_sdhcalThresholds.push_back(2);
      m_sdhcalThresholds.push_back(3);
    }
    else 
    {
      m_sdhcalThresholds.push_back(0.0367023);
      m_sdhcalThresholds.push_back(0.0745279);
      m_sdhcalThresholds.push_back(0.363042);
    }

    unsigned int NHadronicHit1 = 0;
    unsigned int NHadronicHit2 = 0;
    unsigned int NHadronicHit3 = 0;
  
    unsigned int firstNHadronicHit1 = 0; //For the hits contained in the first calo block in Videau geometry
    unsigned int firstNHadronicHit2 = 0;
    unsigned int firstNHadronicHit3 = 0; 

    unsigned int secondNHadronicHit1 = 0; //For the hits contained in the second calo block in Videau geometry
    unsigned int secondNHadronicHit2 = 0;
    unsigned int secondNHadronicHit3 = 0; 

    float initialBarrelHadronic = 0;

    if(pCluster->GetNCaloHits() == 0)
      return pandora::STATUS_CODE_SUCCESS;

    if(correctedEnergy < m_lowEnergyCut)
      return pandora::STATUS_CODE_SUCCESS;

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    bool noShowerHit(true);

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit(*iter);

      if(pCaloHit->GetHitType() == pandora::HCAL)
        {
          if(pCaloHit->GetHitRegion() == pandora::BARREL)
          {
            if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            { 
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.0367023;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }

              if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
                firstNHadronicHit1++;
              else
                secondNHadronicHit1++;
            }
            else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.0745279;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }

              if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
                firstNHadronicHit2++;
              else
                secondNHadronicHit2++;
            }
            else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
            {
              if(m_thetaBefore) //Options for the digi use case
              {
                initialBarrelHadronic+=0.363042;
              }
              else
              {
                initialBarrelHadronic+=pCaloHit->GetInputEnergy();
              }

              if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
                firstNHadronicHit3++;
              else
                secondNHadronicHit3++;
            }
          }
          noShowerHit = false;
        }
    }

    if(noShowerHit)
      return pandora::STATUS_CODE_SUCCESS;

    correctedEnergy-=initialBarrelHadronic; // Pull the initial energy of the HCAL hits from the total energy to correct

    /* std::cout << "NHadronicHit : " << NHadronicHit << std::endl;
    std::cout << "barrelNHadronicHit1 : " << barrelNHadronicHit1 << std::endl;
    std::cout << "barrelNHadronicHit2 : " << barrelNHadronicHit2 << std::endl;
    std::cout << "barrelNHadronicHit3 : " << barrelNHadronicHit3 << std::endl; */

    //Parameters for geometric phi correction
    const float clusterCosPhi(this->GetCosPhi(pCluster)); //Cos phi for the fisrt calo block

    //Angle for the second calo block
    const float PhiPrime(M_PI_4 - std::acos(this->GetCosPhi(pCluster))); //PhiPrime angle with respect to the second calo block

    //CosPhiPrime
    const float clusterCosPhiPrime(fabs(std::cos(PhiPrime))); //Cos phi for the fisrt calo block

    //Sum the corrected number of hits for each tresholds
    NHadronicHit1 = this->GetCorrectedHitNumber(firstNHadronicHit1, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit1, clusterCosPhiPrime);
    NHadronicHit2 = this->GetCorrectedHitNumber(firstNHadronicHit2, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit2, clusterCosPhiPrime);
    NHadronicHit3 = this->GetCorrectedHitNumber(firstNHadronicHit3, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit3, clusterCosPhiPrime);

    const float correctedBarrelEnergy(NHadronicHit1*0.0367023 + NHadronicHit2*0.0745279 + NHadronicHit3*0.363042); //New barrel hadronic energy
    correctedEnergy += correctedBarrelEnergy; //Compute the corrected energy

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float PhiNHitVideau::GetCosPhi(const pandora::Cluster *const pCluster) const
  {
    pandora::CartesianVector centroid(0.f, 0.f, 0.f);
    pandora::CartesianVector zAxis(0.f, 0.f, 1.f);
  
    PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));
    pandora::CartesianVector projectedCentroid(zAxis.GetCrossProduct(centroid.GetCrossProduct(zAxis))); //Project the postion vector of the cluster in the XY-plane 
    float phiAngle = projectedCentroid.GetOpeningAngle(pandora::CartesianVector(0.f, 1.f, 0.f)); //Returns an angle between 0 and PI in rad
    while(phiAngle>M_PI_4/2) //Substract PI/4 until the angle is between -PI/8 and PI/8 rad
    {
        phiAngle-=M_PI_4;
    }

    return fabs(std::cos(phiAngle)); 
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float PhiNHitVideau::GetCorrectedHitNumber(int nHit, float cosPhi) const
  {
	  //std::cout << "nHit: " << nHit << ", cosTheta: " << cosTheta << std::endl;
    return nHit * (1 / (cosPhi));
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode PhiNHitVideau::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
     PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "LowEnergyCut", m_lowEnergyCut));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "UseDigi", m_useDigi));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "ThetaBefore", m_thetaBefore));

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------

  AngleCorrectionPlugin::AngleCorrectionPlugin() :
       m_lowEnergyCut(0.f)
  {
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode AngleCorrectionPlugin::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedEnergy) const
  {
    pandora::FloatVector m_sdhcalThresholds; //Vector to store the thresholds used

    if(m_useDigi)
    {
      m_sdhcalThresholds.push_back(1);
      m_sdhcalThresholds.push_back(2);
      m_sdhcalThresholds.push_back(3);
    }
    else 
    {
      m_sdhcalThresholds.push_back(0.0367023);
      m_sdhcalThresholds.push_back(0.0745279);
      m_sdhcalThresholds.push_back(0.363042);
    }

    unsigned int NHadronicHit = 0;
    unsigned int NHadronicHit1 = 0;
    unsigned int NHadronicHit2 = 0;
    unsigned int NHadronicHit3 = 0;

    unsigned int initialNHit1 = 0;
    unsigned int initialNHit2 = 0;
    unsigned int initialNHit3 = 0;
  
    unsigned int barrelNHadronicHit1 = 0; //For the theta correction in the barrel
    unsigned int barrelNHadronicHit2 = 0;
    unsigned int barrelNHadronicHit3 = 0;

    unsigned int endcapNHadronicHit1 = 0; //For the theta correction in the endcap
    unsigned int endcapNHadronicHit2 = 0; 
    unsigned int endcapNHadronicHit3 = 0; 

    unsigned int firstNHadronicHit1 = 0; //For the phi correction in the first calo block in Videau geometry
    unsigned int firstNHadronicHit2 = 0;
    unsigned int firstNHadronicHit3 = 0; 

    unsigned int secondNHadronicHit1 = 0; //For the phi correction in the second calo block in Videau geometry
    unsigned int secondNHadronicHit2 = 0;
    unsigned int secondNHadronicHit3 = 0; 

    float initialHadronic = 0;

    float lumiHCALEnergy = 0;

    float emEnergy = 0;

    //std::cout << "CORRECTED INIT : " << correctedEnergy << std::endl;

    if(pCluster->GetNCaloHits() == 0)
      return pandora::STATUS_CODE_SUCCESS;
    
    if(correctedEnergy < m_lowEnergyCut)
      return pandora::STATUS_CODE_SUCCESS;

    pandora::CaloHitList clusterCaloHitList;
    pCluster->GetOrderedCaloHitList().FillCaloHitList(clusterCaloHitList);

    bool noShowerHit(true);

    for(pandora::CaloHitList::const_iterator iter = clusterCaloHitList.begin(), endIter = clusterCaloHitList.end() ;
        endIter != iter ; ++iter)
    {
      const pandora::CaloHit *const pCaloHit(*iter);

      if(pCaloHit->GetHitType() == pandora::ECAL) //Only focus on SDHCAL corrections
      {
        //emEnergy += pCaloHit->GetElectromagneticEnergy();
        emEnergy += pCaloHit->GetHadronicEnergy(); //We are looking at hadronic clusters so we need the right correction factor for the hit energy
        noShowerHit = false;
        //std::cout << "ECAL HIT NORMAL VECTOR : " << pCaloHit->GetCellNormalVector() << std::endl;
      }

      else if(pCaloHit->GetHitType() == pandora::HCAL) //Only focus on SDHCAL corrections
      {
        if(pCaloHit->GetHitRegion() == pandora::BARREL)
        {
          //std::cout << pCaloHit->GetCellNormalVector() << std::endl;
          //std::cout << "HCAL HIT NORMAL VECTOR : " << pCaloHit->GetCellNormalVector() << std::endl;
          //std::cout << "HCAL HIT POSITION : " << pCaloHit->GetPositionVector() << std::endl;
          if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          {
            initialHadronic+=pCaloHit->GetHadronicEnergy();
            if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
              firstNHadronicHit1++;
            else
              secondNHadronicHit1++;
          }
          else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          {
            initialHadronic+=pCaloHit->GetHadronicEnergy();
            if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
              firstNHadronicHit2++;
            else
              secondNHadronicHit2++;
          }
          else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          {
            initialHadronic+=pCaloHit->GetHadronicEnergy();
            if(pCaloHit->GetPseudoLayer() == (pCaloHit->GetLayer()+30)) //If pseudolayer!=layer+30, means the hit is in the other block
              firstNHadronicHit3++;
            else
              secondNHadronicHit3++;
          }
        }
        else if(pCaloHit->GetHitRegion() == pandora::ENDCAP)
        {
          if(fabs(m_sdhcalThresholds.at(0) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          { 
            endcapNHadronicHit1++;
            initialHadronic+=pCaloHit->GetHadronicEnergy();
          }
          else if(fabs(m_sdhcalThresholds.at(1) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          {
            endcapNHadronicHit2++;
            initialHadronic+=pCaloHit->GetHadronicEnergy();
          }
          else if(fabs(m_sdhcalThresholds.at(2) - pCaloHit->GetInputEnergy()) < std::numeric_limits<float>::epsilon())
          {
            endcapNHadronicHit3++;
            initialHadronic+=pCaloHit->GetHadronicEnergy();
          }
          else
          {
            lumiHCALEnergy+=pCaloHit->GetHadronicEnergy();
          }
        }
        noShowerHit = false;
      }
    }

    if(noShowerHit)
      return pandora::STATUS_CODE_SUCCESS;


    barrelNHadronicHit1 = firstNHadronicHit1 + secondNHadronicHit1; //Sum the hits in the barrel
    barrelNHadronicHit2 = firstNHadronicHit2 + secondNHadronicHit2;
    barrelNHadronicHit3 = firstNHadronicHit3 + secondNHadronicHit3;

    /* std::cout << "N1 premier stave : " << firstNHadronicHit1 << std::endl;
    std::cout << "N2 premier stave : " << firstNHadronicHit2 << std::endl;
    std::cout << "N3 premier stave : " << firstNHadronicHit3 << std::endl;

    std::cout << "N1 deuxieme stave : " << secondNHadronicHit1 << std::endl;
    std::cout << "N2 deuxieme stave : " << secondNHadronicHit2 << std::endl;
    std::cout << "N3 deuxieme stave : " << secondNHadronicHit3 << std::endl; */

    initialNHit1 = barrelNHadronicHit1 + endcapNHadronicHit1; //Compute the initial number of hits in sdhcal
    initialNHit2 = barrelNHadronicHit2 + endcapNHadronicHit2;
    initialNHit3 = barrelNHadronicHit3 + endcapNHadronicHit3;

    /* std::cout << "NHadronicHit : " << NHadronicHit << std::endl;
    std::cout << "barrelNHadronicHit1 : " << barrelNHadronicHit1 << std::endl;
    std::cout << "barrelNHadronicHit2 : " << barrelNHadronicHit2 << std::endl;
    std::cout << "barrelNHadronicHit3 : " << barrelNHadronicHit3 << std::endl;

    std::cout << "endcapNHadronicHit1 : " << endcapNHadronicHit1 << std::endl;
    std::cout << "endcapNHadronicHit2 : " << endcapNHadronicHit2 << std::endl;
    std::cout << "endcapNHadronicHit3 : " << endcapNHadronicHit3 << std::endl; */

    //TO UNCOMMENT WHEN NOT USING THE FIXDIRECTION DISPLACED TESLA

     //Parameters for geometric phi correction
    const float clusterCosPhi(this->GetCosPhi(pCluster)); //Cos phi for the fisrt calo block

    //std::cout << "Phi : " << std::acos(clusterCosPhi) * (180 /M_PI) << std::endl;

    //Angle for the second calo block
    const float PhiPrime(M_PI_4 - std::acos(this->GetCosPhi(pCluster))); //PhiPrime angle with respect to the second calo block
    //std::cout << "Phi Prime : " << PhiPrime * (180 /M_PI)<< std::endl;

    //CosPhiPrime
    const float clusterCosPhiPrime(fabs(std::cos(PhiPrime))); //Cos phi for the second calo block

    //Parameters for geometric theta correction
    const float clusterCosTheta(this->GetCosTheta(pCluster)); //Cos theta for the endcap correction
    const float thetaAngle(std::acos(clusterCosTheta)); //Theta angle
    const float clusterSinTheta(std::sin(thetaAngle)); //Sin thecosOrSinAngla for the barrel correction 

    //Sum the corrected number of hits for each tresholds : Correction for endcap and barrel
    /* NHadronicHit1 = initialNHit1 + this->GetCorrectedHitNumber(barrelNHadronicHit1, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit1, clusterCosTheta) + this->GetCorrectedHitNumber(firstNHadronicHit1, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit1, clusterCosPhiPrime);
    NHadronicHit2 = initialNHit2 + this->GetCorrectedHitNumber(barrelNHadronicHit2, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit2, clusterCosTheta) + this->GetCorrectedHitNumber(firstNHadronicHit2, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit2, clusterCosPhiPrime);
    NHadronicHit3 = initialNHit3 + this->GetCorrectedHitNumber(barrelNHadronicHit3, clusterSinTheta) + this->GetCorrectedHitNumber(endcapNHadronicHit3, clusterCosTheta) + this->GetCorrectedHitNumber(firstNHadronicHit3, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit3, clusterCosPhiPrime);
 
 */
    //Sum the corrected number of hits for each tresholds : Correction for barrel only
    NHadronicHit1 = initialNHit1 + this->GetCorrectedHitNumber(barrelNHadronicHit1, clusterSinTheta) + this->GetCorrectedHitNumber(firstNHadronicHit1, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit1, clusterCosPhiPrime);
    NHadronicHit2 = initialNHit2 + this->GetCorrectedHitNumber(barrelNHadronicHit2, clusterSinTheta) + this->GetCorrectedHitNumber(firstNHadronicHit2, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit2, clusterCosPhiPrime);
    NHadronicHit3 = initialNHit3 + this->GetCorrectedHitNumber(barrelNHadronicHit3, clusterSinTheta) + this->GetCorrectedHitNumber(firstNHadronicHit3, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit3, clusterCosPhiPrime);
 


    //Sum the corrected number of hits for each tresholds : Correction for barrel only, phi only
    /* NHadronicHit1 = initialNHit1 + this->GetCorrectedHitNumber(firstNHadronicHit1, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit1, clusterCosPhiPrime);
    NHadronicHit2 = initialNHit2 + this->GetCorrectedHitNumber(firstNHadronicHit2, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit2, clusterCosPhiPrime);
    NHadronicHit3 = initialNHit3 + this->GetCorrectedHitNumber(firstNHadronicHit3, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit3, clusterCosPhiPrime);
  */


    //For fixdirection displaced Tesla or no angular correction 
    /* NHadronicHit1 = initialNHit1;
    NHadronicHit2 = initialNHit2;
    NHadronicHit3 = initialNHit3; */


    /* NHadronicHit1 = initialNHit1 + this->GetCorrectedHitNumber(firstNHadronicHit1, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit1, clusterCosPhiPrime);
    NHadronicHit2 = initialNHit2 + this->GetCorrectedHitNumber(firstNHadronicHit2, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit2, clusterCosPhiPrime);
    NHadronicHit3 = initialNHit3 + this->GetCorrectedHitNumber(firstNHadronicHit3, clusterCosPhi) + this->GetCorrectedHitNumber(secondNHadronicHit3, clusterCosPhiPrime);
 */

    


    //Calculate the corrected total number of hits
    NHadronicHit = NHadronicHit1 + NHadronicHit2 + NHadronicHit3;

    //std::cout << "NHit corrected : " << NHadronicHit << std::endl;

    pandora::FloatVector m_energyConstantParameters;


// Split method : 

   /*  if(NHadronicHit <= 400) //Test de split propre avec ajustement sur les deux ranges pour Nhcal = 600 et chevauchement des formules : NOUVELLE CALIBRATION, Split 400 Quad APRIL Overlap
    {
      m_energyConstantParameters.push_back(0.0712495);  //Fit pour Nhcal <= 600
      m_energyConstantParameters.push_back(-0.000186449);
      m_energyConstantParameters.push_back(1.97156e-07);
      m_energyConstantParameters.push_back(0.0153121);
      m_energyConstantParameters.push_back(0.00045658);
      m_energyConstantParameters.push_back(-6.3797e-07);
      m_energyConstantParameters.push_back(1.28742e-12);
      m_energyConstantParameters.push_back(0.00100913);
      m_energyConstantParameters.push_back(-5.59527e-07);
    }
    else
    {
      m_energyConstantParameters.push_back(0.0350654);  // Fit pour Nhcal > 400 
      m_energyConstantParameters.push_back(-3.84159e-05);
      m_energyConstantParameters.push_back(2.40987e-08);
      m_energyConstantParameters.push_back(0.137626);
      m_energyConstantParameters.push_back(-0.00012783);
      m_energyConstantParameters.push_back(7.27967e-08);
      m_energyConstantParameters.push_back(1e-10);
      m_energyConstantParameters.push_back(0.00113873);
      m_energyConstantParameters.push_back(-6.63919e-07);
    }
 */
    //Quad v5 ajustee 

    m_energyConstantParameters.push_back(0.063000);    // était 0.0645514 → -2.4% Calibration test v5bis ajuste
    m_energyConstantParameters.push_back(-0.000117);   // inchangé (très léger)
    m_energyConstantParameters.push_back(7.1818e-08);  // inchangé
    m_energyConstantParameters.push_back(0.041000);    // était 0.0422478 → -2.95%
    m_energyConstantParameters.push_back(0.000139);    // légère baisse
    m_energyConstantParameters.push_back(-9.17877e-08); // inchangé
    m_energyConstantParameters.push_back(1e-10);        // inchangé (négligeable)
    m_energyConstantParameters.push_back(0.001105);     // était 0.00112138 → -1.4%
    m_energyConstantParameters.push_back(-6.43333e-07); // inchangé


    //ML with sklearn degree 2, new calibration dataset 26/06/25
    //const float hadEnergy(0.030334*NHadronicHit1 + 0.086529*NHadronicHit2 + 0.320575*NHadronicHit3 + 0.000014*NHadronicHit1*NHadronicHit1 + 0.000190*NHadronicHit1*NHadronicHit2 - 0.000969*NHadronicHit1*NHadronicHit3 - 0.000403*NHadronicHit2*NHadronicHit2 + 0.000500*NHadronicHit2*NHadronicHit3 + 0.004948*NHadronicHit3*NHadronicHit3);

    

    // Quadratic correction
    const float alpha(m_energyConstantParameters.at(0) + m_energyConstantParameters.at(1)*NHadronicHit + m_energyConstantParameters.at(2)*NHadronicHit*NHadronicHit);
    const float beta(m_energyConstantParameters.at(3) + m_energyConstantParameters.at(4)*NHadronicHit + m_energyConstantParameters.at(5)*NHadronicHit*NHadronicHit);
    const float gamma(m_energyConstantParameters.at(6) + m_energyConstantParameters.at(7)*NHadronicHit + m_energyConstantParameters.at(8)*NHadronicHit*NHadronicHit);
    const float hadEnergy(NHadronicHit1*alpha + NHadronicHit2*beta + NHadronicHit3*gamma);
    


    // Linear formula
          // const float hadEnergy(NHadronicHit1*0.0367023 + NHadronicHit2*0.0745279 + NHadronicHit3*0.363042); //Initial parameters corresponding to the Energy factors
          

    correctedEnergy = lumiHCALEnergy + emEnergy + hadEnergy;
    

    return pandora::STATUS_CODE_SUCCESS;
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float AngleCorrectionPlugin::GetCosTheta(const pandora::Cluster *const pCluster) const
  {
    pandora::CartesianVector centroid(0.f, 0.f, 0.f);
    PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));

    //std::cout << "CENTROID : " << centroid << std::endl;

    return fabs(centroid.GetCosOpeningAngle(pandora::CartesianVector(0.f, 0.f, 1.f)));
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float AngleCorrectionPlugin::GetCosPhi(const pandora::Cluster *const pCluster) const
  {
    pandora::CartesianVector centroid(0.f, 0.f, 0.f);
    pandora::CartesianVector zAxis(0.f, 0.f, 1.f);
  
    PANDORA_THROW_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ClusterHelper::GetCentroid(pCluster, centroid));
    pandora::CartesianVector projectedCentroid(zAxis.GetCrossProduct(centroid.GetCrossProduct(zAxis))); //Project the postion vector of the cluster in the XY-plane 
    float phiAngle = projectedCentroid.GetOpeningAngle(pandora::CartesianVector(0.f, 1.f, 0.f)); //Returns an angle between 0 and PI in rad
    while(phiAngle>M_PI_4/2) //Substract PI/4 until the angle is between -PI/8 and PI/8 rad
    {
        phiAngle-=M_PI_4;
    }

    return fabs(std::cos(phiAngle)); 
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  float AngleCorrectionPlugin::GetCorrectedHitNumber(int nHit, float cosOrSinAngle) const
  {
	  //std::cout << "nHit: " << nHit << ", cosTheta: " << cosTheta << std::endl;
    //std::cout << "Nouveau nombre de hits : " << nHit * ( (1. / cosOrSinAngle) - 1 ) << std::endl;
    return nHit * ( (1. / cosOrSinAngle) - 1 );
  }

  //------------------------------------------------------------------------------------------------------------------------------------------

  pandora::StatusCode AngleCorrectionPlugin::ReadSettings(const pandora::TiXmlHandle xmlHandle)
  {
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "LowEnergyCut", m_lowEnergyCut));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "UseDigi", m_useDigi));

    return pandora::STATUS_CODE_SUCCESS;
  }

//------------------------------------------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------------------------------------------  

CleanCluster::CleanCluster() :
    m_minCleanHitEnergy(0.5f),
    m_minCleanHitEnergyFraction(0.01f),
    m_minCleanCorrectedHitEnergy(0.1f)
{
}

//------------------------------------------------------------------------------------------------------------------------------------------

pandora::StatusCode CleanCluster::MakeEnergyCorrections(const pandora::Cluster *const pCluster, float &correctedHadronicEnergy) const
{
    const unsigned int firstPseudoLayer(this->GetPandora().GetPlugins()->GetPseudoLayerPlugin()->GetPseudoLayerAtIp());

    const float clusterHadronicEnergy(pCluster->GetHadronicEnergy());

    if (std::fabs(clusterHadronicEnergy) < std::numeric_limits<float>::epsilon())
        throw pandora::StatusCodeException(pandora::STATUS_CODE_FAILURE);

    bool isFineGranularity(true);
    const pandora::OrderedCaloHitList &orderedCaloHitList(pCluster->GetOrderedCaloHitList());

    // Loop over all constituent inner layer fine granularity hits, looking for anomalies
    for (pandora::OrderedCaloHitList::const_iterator layerIter = orderedCaloHitList.begin(), layerIterEnd = orderedCaloHitList.end();
        (layerIter != layerIterEnd) && isFineGranularity; ++layerIter)
    {
        const unsigned int pseudoLayer(layerIter->first);

        for (pandora::CaloHitList::const_iterator hitIter = layerIter->second->begin(), hitIterEnd = layerIter->second->end();
            hitIter != hitIterEnd; ++hitIter)
        {
            const pandora::CaloHit *const pCaloHit = *hitIter;

            if (this->GetPandora().GetGeometry()->GetHitTypeGranularity((*hitIter)->GetHitType()) > pandora::FINE)
            {
                isFineGranularity = false;
                break;
            }

            const float hitHadronicEnergy(pCaloHit->GetHadronicEnergy());

            if ((hitHadronicEnergy > m_minCleanHitEnergy) && (hitHadronicEnergy / clusterHadronicEnergy > m_minCleanHitEnergyFraction))
            {
                // Calculate new energy from surrounding layers
                float energyInPreviousLayer(0.);

                if (pseudoLayer > firstPseudoLayer)
                    energyInPreviousLayer = this->GetHadronicEnergyInLayer(orderedCaloHitList, pseudoLayer - 1);

                float energyInNextLayer(0.);

                if (pseudoLayer < std::numeric_limits<unsigned int>::max())
                    energyInNextLayer = this->GetHadronicEnergyInLayer(orderedCaloHitList, pseudoLayer + 1);

                const float energyInCurrentLayer = this->GetHadronicEnergyInLayer(orderedCaloHitList, pseudoLayer);

                // Calculate new energy estimate for hit and update cluster best energy estimate
                float energyInAdjacentLayers(energyInPreviousLayer + energyInNextLayer);

                if (pseudoLayer > firstPseudoLayer)
                    energyInAdjacentLayers /= 2.f;

                float newHitHadronicEnergy(energyInAdjacentLayers - energyInCurrentLayer + hitHadronicEnergy);
                newHitHadronicEnergy = std::max(newHitHadronicEnergy, m_minCleanCorrectedHitEnergy);

                if (newHitHadronicEnergy < hitHadronicEnergy)
                    correctedHadronicEnergy += newHitHadronicEnergy - hitHadronicEnergy;
            }
        }
    }

    return pandora::STATUS_CODE_SUCCESS;
}

//------------------------------------------------------------------------------------------------------------------------------------------

float CleanCluster::GetHadronicEnergyInLayer(const pandora::OrderedCaloHitList &orderedCaloHitList, const unsigned int pseudoLayer) const
{
	pandora::OrderedCaloHitList::const_iterator iter = orderedCaloHitList.find(pseudoLayer);

    float hadronicEnergy(0.f);

    if (iter != orderedCaloHitList.end())
    {
        for (pandora::CaloHitList::const_iterator hitIter = iter->second->begin(), hitIterEnd = iter->second->end(); hitIter != hitIterEnd; ++hitIter)
        {
            hadronicEnergy += (*hitIter)->GetHadronicEnergy();
        }
    }

    return hadronicEnergy;
}

//------------------------------------------------------------------------------------------------------------------------------------------

pandora::StatusCode CleanCluster::ReadSettings(const pandora::TiXmlHandle xmlHandle)
{
    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "MinCleanHitEnergy", m_minCleanHitEnergy));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "MinCleanHitEnergyFraction", m_minCleanHitEnergyFraction));

    PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
        "MinCleanCorrectedHitEnergy", m_minCleanCorrectedHitEnergy));

    return pandora::STATUS_CODE_SUCCESS;
}

}

